### PR TITLE
Stratholme - Rockwing Gargoyle / Rockwing Screecher

### PR DESCRIPTION
**Pull request by Tobschinski**
- added movement to (7 pats)
- pooled spawns (50/50 -> gargoyle / screecher)
- added creatures and movement for rare spawn Stonespine

Source: Data based on retail

### CODE REVIEW

**Comment by Tobschinski** [comment]
@cala 

One thing is missing and I am not sure how to do it properly.

[Stonespine](http://www.wowhead.com/npc=10809), the rare gargoyle, could spawn as any of these patrols. However, he is considered unique and should never be up twice. So just adding him to the pools would be not correct.

Are you more familiar with pool of pools than I am, or even have a better idea? Would be nice to know.

And the updated template is still missing, these patrols should move faster.

**Comment by cala** [comment]
Thank you for this pull request. You are doing a great work. I sent you a PM about it a few days ago on cmangos boards.

Regarding Stonspine, I understand what the problem is. It may be fixable with pool of pools. I have to think of this first.

**Comment by cala** [comment]
After putting some thoughts on this, I think the only way to have the intended behaviour via DB (pools of pools) is to create a pool of pools for every possible combinaison. I will calculate how many of them to see if we do this by DB or if a SD2 solution is preferable.

For example, this is similar to the Emerald Dragons spawning: currently their spawns are statics while they should randomly spawn in one of the four spots. If we want to do this by DB, this is 4! pools to create for only 4 NPCs... A bit to much of work in my opinion, so SD2 could be a better solution there.

**Comment by evil-at-wow** [comment]
I agree that the pool system does not allow us to do what we really want (or at least not always in a practical way). I've recently run into its limits too on several occasions when working on DM West spawns. It's not that hard to end up with a few dozen child pools for every combination, and that's certainly not the intended use.

I'm sure using SD2 would work in this case, but I feel moving every single case we can't easily handle with the core's pool system to SD2 would be the wrong solution. I feel there should be ways to improve the pool system in the core. I'll think about that, and poke our beloved core devs when I have something to discuss.

**Comment by cala** [comment]
>  I've recently run into its limits too on several occasions when working on DM West spawns. It's not that hard to end up with a few dozen child pools for every combination, and that's certainly not the intended use.

This reminds me that I still have to test the big DM East update you gave me. I thus officially mark it as part of next Classic DB release in order to not forget it again. Sorry.

**Comment by evil-at-wow** [comment]
No worries @cala, and no need to apologize. One can only do so much in a day after all. In the meantime, I started doing work for the West and North wings, but like I said, I ran into some issues. But I'll get there, no worries.

**Comment by cala** [comment]
I tried different approaches with the pool system, but I can not find a way to have Stonespine added as described above.

So, I think to push this PR as it is and postponed the Stonespine later (the fact it is missing is kept by #195 )

I put some thoughts into the suggestion made by @evil-at-wow regarding improving the pool system. I think we could have some use of a `creature_templates_ratio`. The idea is to have a structure like (creature_entry, alternate_entry, ratio, max_alternate_allowed), with the primary key being on alternate_entry.
When the core would have to spawn a NPC with `creature_entry`, it would have `ratio` chances to spawn `alternate_entry` instead, capped to `max_alternate_allowed`.
This would cover cases where different creatures share a same spawn points (like Fire Lord / Lava Annihilator in Molten Core, the gargoyles here). Or more commonly in the open world, like kobolds in caves for instance, when a kobold "miner" is killed, sometime a kobold "geomancer" is spawned instead.
Obviously, the `max_alternate_allowed = 1` would cover cases like Stonespine.
Such system would also reduce the size of `creature` table. Pools like the ones above (two types of gargoyles) would be handled by only one entry in `creature`, the core "morphing" the creature into its alternate entry from data in `creature_template`, thus sharing the same guid. Same approach for the waypoints: they can share it. The only "blocking" point would be the `creature_addon` creatures using this pool system could only use `creature_addon_template` or ACID.

**Comment by Tobschinski** [comment]
I've thought,  adding Stonespine to just one of those pats, would be the best temp solution.

Soon, soon, the finals have started already :)

**Comment by cala** [comment]
This is also an acceptable solution. I will add this spawn to one of the regular gargoyles pools.
You can focus on your final parts of the World Cup. :P

**Comment by evil-at-wow** [comment]
Interesting idea, @cala. I have been exploring other - more general - ways to accomplish the same thing, which also solve some other issues I ran into that your idea is not covering.

But one thing our ideas have in common is that they reduce the redundant data in the creature (or gameobject) table. I'm glad we both feel this is likely a must have, because as you point out, there are **many** cases where one of several creatures should spawn (even though that's currently often not the case).

We see the same fact with gameobjects. For instance, most ore deposit spawn points have 3 to 5 gameobject entries because different ores could spawn there. That's probably were the alternatives you propose could introduce some unused data. If you need up to three or four alternatives, we'll be adding several extra columns, unused by most normal gameobject entries.

Waypoints and creature_addon data was also the tricky point in my ideas. Nothing that can't be solved of course, but then again we don't want to change half of the core obviously.

Anyway, I'm hoping I'll be able to make a post with some ideas by the end of the week. Coding could start shortly after that, depending on feedback.

**Comment by cala** [comment]
Yes, I did not mention that I have the same thing in mind for gameobjects, but the mineral nodes was precisely what I had in mind for those.
Good to see we are like-minded on this matter. :)

**Comment by Schmoozerd** [comment]
well, currently the system is for one mineral node with alternatives A, B, C just to have the 3 lines for A,B,C in go table and the lines in the pool.
I doubt that this requires a different handling. Especially that @neo2003 did think about the mineral nodes when creating the pool system. So i assume that for some reasons the current system was (especially) for GO-spawning about the best realaistic solution.

**Comment by Tobschinski** [comment]
Still not done here, I'll have to update their movement_speed and see if they are walking or running.

**Comment by cala** [comment]
Accepted as it is, thank you. The missing spawns for Stonespine will have to wait for the core to be able to handle this case. The speed update can still be done later.

**Pull request closed without merging**
