### PR TITLE
Correcting The Second Rebellion Quest Chain

### PR DESCRIPTION
**Pull request by Sinoxan**
- Quest Chain:
- 203 The Second Rebellion
- 204 Bad Medicine
- 574 Special Forces
- 202 Colonel Kurzen

### CODE REVIEW

**Comment by cala** [comment]
Thank you for this. From http://wowhead.com/quest=204#comments:id=264347 I understand that quests 203 and 204 are not coming one after the other but are available at the same time. And that quest 574 requires both quests 203 and 204 to be completed before being available.
wowwiki/wowpedia seems to think that quest 204 is not related to the other. Old wow.allakhazam agrees with you. I also think that you are right, but having another source, would be nice. Maybe @Tobschinski or @swater96 and their strategy guides can give us some input?

**Comment by Sinoxan** [comment]
The Master Guide list The Second Rebellion and Bad Medicine as having no prerequisite. Colonel Kurzen needs Special Forces, and Special Forces needs The Second Rebellion.

**Comment by Sinoxan** [comment]
Looking at the wowhead comments over the three quests The Second Rebellion and Bad Medicine are both available and prereqs for Special Forces.  I'll try and update this sometime today.

**Comment by Tobschinski** [comment]
Sadly, the Master Guide will not be helpful if a quest has more than one prerequisite. The column has just space for one quest (maybe the one with the highest level, or the highest id, I didn't check that ...). 
(e.g.  Raptor Mastery -> Big Game Hunter (Tiger and Panther Mastery are missing here)

**Comment by cala** [comment]
Accepted, thank you.

**Pull request closed without merging**
