### PR TITLE
Correcting Quest Chain, Levels, Type

### PR DESCRIPTION
**Pull request by Sinoxan**
- Quest Chain:
- 606 L41 R30 Scaring Shaky
- 607 L41 R30 Return to MacKinley
- 609 L44 R30 Voodoo Dues
- 613 L44 R31 Cracking Maury's Foot  (GROUP)

### CODE REVIEW

**Comment by Tobschinski** [comment]
Greetings, at least the qlvl and minlvl have already been taken care of.

**Comment by Sinoxan** [comment]
The chain is like this on allakazham and the wowpedia pages confirm this, all 4 pages created by one reputable editor at the same time so it's reliable.  Also, just by looking at the quest descriptions you can tell it's a chain.

**Comment by cala** [comment]
I think @Tobschinski was meaning that he intends to change some parts of these quests (reputation, I guess) and that he won't have to look to the quest levels thanks to you. :)

**Comment by cala** [comment]
Accepted, thank you.

**Comment by Tobschinski** [comment]
Oh I just noticed, damn, I'm late.
Well I just wanted to point, that his db is probably not up to date, as the levels have been taken care of in https://github.com/classicdb/database/commit/cb865ea55161623812146cb64711b025020c5eec

I would not mind since the updates to the levels won't do anything ...
But at least 

```
+UPDATE `quest_template` SET `MinLevel` = 31          WHERE `entry` = 613;
```

sets a MinLevel that is different from the MasterGuide and wowhead (they state 30). In fact it is very rare, that jumps occur in the minimum level of a quest chain. And even the previous quest
has the same questlevel (44).

**Comment by Sinoxan** [comment]
It was up to date when I committed it, I just put in updates for everything just in case, if it's already up to date then it won't change anything but just in case thought I might as well put a commit updating all parts.

**Comment by Tobschinski** [comment]
Ah okay, I am sorry. I asked just to be sure.

What do you think of the quest 613?

**Comment by Sinoxan** [comment]
I saw that it was 30 in the master guide but archived pages on allakhazam, thottbot and wowpedia list it as being 31.  I think Blizzard agreed with you and must have changed it at some point in TBC or WotLK.

**Comment by Sinoxan** [comment]
@cala What's your opinion on databases and wowpedia versus the master guide?

**Comment by cala** [comment]
As time goes by, it is increasingly difficult to find reliable sources for Classic, so we should use every one while knowing their strengths and flaws.

**Strategy guides**
STRENGTHS: the data usually come from the game companies, so they are kind of official and as such very valuable
FLAWS: the data are set in stone. They usually are slightly out of date when the guide ships because in the meantime, the game company released some patch. So, day after day it is harder to tell which parts are outdated and which ones are still valid.

**wikis**
STRENGTHS: they are very alive and as such pretty up to date. They have an awesome history function helping to track what change occured and when
FLAWS: they are not official in any way, values are manually added by users, which can lead to errors, and if errors are not spotted by someone else, they remain there and become the "right" value

**databases**
STRENGTHS: they get their data from retail servers and have a statistical approach, they are usually up to date
FLAWS: there is no history at all so it is hard to dig, the data are auto collected and as such subject to errors (bugs or wrong parsing algorithm, mainly after a patch release), statistical unaccuracy (quests items drop rate for instance...), they are driven by money so they want to bring the most people in, meaning they value quantity over quality

This is why I usually try to check several sources before choosing to update (or not) a value. In doubt, do not forget to look at other DB projects, they usually use sniff data.

**Pull request closed without merging**
