### PR TITLE
Pet Patch 1.1: Guardian Goodies

### PR DESCRIPTION
**Pull request by Phatcat**
For what is a core update without a DB update.

@cala

Ref: https://github.com/cmangos/mangos-classic/pull/151

---

This change is [Reviewable](https://reviewable.io/reviews/classicdb/database/869)

### CODE REVIEW

**Comment by Phatcat** [comment]
Just remembered the goblin engineering 'trinket' guardian (the bomb thing) is not supposed to melee either.

**Comment by cala** [comment]
:+1:

**Comment by Phatcat** [comment]
I just gotta remember that I forgot to give flags to the goblin mine thing; oh well, guardians are not nearly done yet either, many of them have the wrong scale and seem to have their damage off anyways.

Currently working on pet evade and threat list functionality for non controllable pets. I'll let you know when I have something concrete enough to test =)

**Comment by Phatcat** [comment]
> Id: 13258
> Name: Summon Goblin Bomb
> Description: Creates a mobile bomb that charges the nearest enemy and explodes for $13259s1 fire damage.
> General info
> Category = 0, SpellIconId = 162, ActiveIconId = 0, SpellVisual = (2206, 0)
> SpellFamilyName = SPELLFAMILY_GENERAL, SpellFamilyFlags = 0x0000000000000000
> SpellSchoolMask = 1 (SCHOOL_MASK_PHYSICAL, SCHOOL_MASK_ALL)
> DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
> PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
> Attributes
> Attributes: 0x00040090 (SPELL_ATTR_UNK4, SPELL_ATTR_UNK7, SPELL_ATTR_UNK18)
> Advanced info
> Skill (Id 202) "Engineering"
> ReqSkillValue = 1
> Forward Spell = 0
> MinMaxValue (0, 0)
> CharacterPoints (0, 0)
> Spell Level = 40, BaseLevel 40, MaxLevel 0, MaxTargetLevel 0
> Category = 0
> DispelType = 0 (DISPEL_NONE)
> Mechanic = 0 (MECHANIC_NONE)
> SpellRange (Id 1) "Self Only"
> MinRange = 0
> MaxRange = 0
> CastingTime (Id 2) = 0.25
> Duration: ID (3) 60000, 0, 60000
> Interrupt Flags: 0x00000000, AuraIF 0x00000000, ChannelIF 0x00000000
> Chance = 101, charges - 0
> Effects
> Effect 0:
> Id: 28 (SPELL_EFFECT_SUMMON)
> BasePoints = 1
> Targets (18, 0) (TARGET_EFFECT_SELECT, NO_TARGET)
> EffectMiscValueA = 8937
> EffectMiscValueB = 61
> Effect 1:
> NO EFFECT
> Effect 2:
> NO EFFECT

So it's creature by id **8937** that is the goblin mine (which I forgot in this update) - will include in the next update to creature_template (unless someone beats me to it, which they are more than welcome to)

**Comment by Phatcat** [comment]
> Attributes: 0x00040090 (SPELL_ATTR_UNK4, SPELL_ATTR_UNK7, SPELL_ATTR_UNK18)

By the way that's a lovely set of unknowns there...

**Comment by Phatcat** [comment]
Battle chicken still however takes the prize:

> Id: 13166
> Name: Battle Chicken
> Description: Creates a Battle Chicken that will fight for you for $d or until it is destroyed.
> General info
> Category = 0, SpellIconId = 90, ActiveIconId = 0, SpellVisual = (74, 0)
> SpellFamilyName = SPELLFAMILY_GENERAL, SpellFamilyFlags = 0x0000000000000000
> SpellSchool = 0 (SPELL_SCHOOL_NORMAL)
> DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
> PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
> Attributes
> Attributes: 0x00000080 (SPELL_ATTR_UNK7)
> Advanced info
> Skill (Id 202) "Engineering"
> ReqSkillValue = 1
> Forward Spell = 0
> MinMaxValue (0, 0)
> CharacterPoints (0, 0)
> Spell Level = 45, BaseLevel 45, MaxLevel 0, MaxTargetLevel 0
> Category = 0
> DispelType = 0 (DISPEL_NONE)
> Mechanic = 0 (MECHANIC_NONE)
> SpellRange (Id 1) "Self Only"
> MinRange = 0
> MaxRange = 0
> CastingTime (Id 1) = 0.00
> Duration: ID (23) 90000, 0, 90000
> Interrupt Flags: 0x00000000, AuraIF 0x00000000, ChannelIF 0x00000000
> Chance = 101, charges - 0
> Effects
> Effect 0:
> Id: 74 (SPELL_EFFECT_SUMMON_TOTEM)
> BasePoints = 800
> Targets (18, 0) (TARGET_EFFECT_SELECT, NO_TARGET)
> EffectMiscValue = 8836
> Effect 1:
> NO EFFECT
> Effect 2:
> NO EFFECT

That's right.

> Id: 74 (SPELL_EFFECT_SUMMON_TOTEM)

Blizzard made themselves hackfix their own system to make this work instead of just doing a spell_effect_summon or spell_effect_summon_guardian. That's some good work right there. :+1:

**Pull request closed without merging**
