### PR TITLE
Hallow's End Rework

### PR DESCRIPTION
**Pull request by Zingzah**
This PR attempts to fix/highlight the issues effecting the Hallow's End event for classic cmangos.  The Hallow's End currently is non-functional with:

No Wickerman Festival spawned (except for Darkcaller Yanka)
Lolly Quests (Jesper and Spoops) non-obtainable/completable
Non-lolly quests unavailable/non-completable
Wickerman Festival event not implemented
Objects from later versions of Hallow's End present
Pumpkin Bags not in loot tables
Various Npcs with incorrect placement and missing gossips, etc.

Hallow's End was introduced in October 2005 with patch 1.8 and so for patch 1.12 this was the second Hallow's End in the history of the game.  In this incarnation of the event there were was no headless horseman. There was no putting out fires, scarlet monastery event or shade of the horseman questlines.  The first time these were encountered was in 2007. Southshore was the focus for both horde and alliance quests and the Wickerman festival was only outside Undercity. This was present until 2011 when the event was reworked to what is the current event.   The lolly quests from Jesper and Spoops were the only commonality between the classic version and the current one.

[](http://web.archive.org/web/20061129092910/http://www.wowwiki.com/Hallow%2527s_End)
https://www.youtube.com/watch?v=iGgnk5yAT4k
http://casualwow.blogspot.com.au/2006_10_01_archive.html
https://harpysnest.wordpress.com/category/festival-fun-and-frolics/page/4/

This PR has been organised into the following categories:
Cleanup
Wickerman Festival
Lolly Quests
Non-lolly Quests
Pumpkin Bags
Sylvanas Event
Cleanup

**Cleanup**

This object (186720) was present in the game from 2007 onwards and doesn't belong in this version of the event hence it is being removed.  It was used for the fire training quest at the start of the Shade of the Horse man questline.

**The Wickerman Festival**

This festival was unchanged from 2005 to 2010 (except for the Banshee Queen model).  It is currently unspawned on classic except for an incorrectly placed Darkcaller Yanka npc.  Most npc and object placements were from trinity core and a few from ytdb (Thanks to both) and a few bonfires were estimates from the screenshots and videos below:

https://www.youtube.com/watch?v=iGgnk5yAT4k
2967223233_69cafbca73_z
ashes 2
hedecwickermanfire
wowh08

In addition, Wickerman Guardians have had their disease clouds restored and will correctly drop a Wickerman Guardian Ember when killed. Darkcaller Yanka's correct gossip has been restored.

*_Lolly Quests
*_
These quests involve Jesper and Spoops. They require the player to visit innkeepers in each capital, perform an emote and receive their lollies.  Currently the initial quest from Jesper(8311) is unavailable as are the quests from the alliance capital innkeepers.  The innkeepers also do not respond to the correct emote to complete the quest.  All of these issues have been corrected.

Spoops has the quest(8312) available but is incorrectly designated an innkeeper with gossip.  These have been corrected.  Npcs involved in these quests have available their respective quests once quest 8312 is accepted but are unable to complete these quests upon receiving the correct emote.  These issues have been corrected.
jesper
spoops9ay4vn

*_Non-lolly Quests *_

Alliance
The Power of Pine - 8373

This quest currently autocompletes on using the given item (Stink Bomb Cleaner 20604) whether there is a stink bomb present/within range or not.  It also doesn't despawn the Stink Bomb and associated cloud.  The autocomplete feature has not been corrected but when within range cleaner will now despawn the stink bomb + cloud.  The autocomplete feature is built into the spell triggered by the cleaner.  This possibly is a core issue where the spell needs conditions added (range to stinkbomb, using the cleaning item) to triggered this part.

pop2
powerofpine 3

Crashing the Wickerman Festival - 1658

Currently this quest is unable to be completed.  The correct areatrigger has been added and will now complete the quest when approached.

In addition, Sargeant Hartman's position has been adjusted (estimated) and gossip added to match the following screenshots:
hedecsergeanthartman 1
powerofpine 3

Horde

Stinking Up Southshore - 1657

This quest is currently not able to be completed due to the toss stink bomb spell not being registered.  This has been corrected but although quest objectives are displayed as complete, the quest complete button upon handing in to Darkcaller Yanka is unhighlighted.  This maybe be fixed by adjusting a quest parameter that hasn't yet been considered.

The option to purchase more stink bombs once the quest is completed has been added to Darkcaller Yanka.

Rotten Eggs - This quest (8322) and it's follow up quest Ruined Kegs(8409) are working as intended.  However the quest giving object Keg (180570) should be unavailable outside event times and has been swapped with non-quest Keg 180575 to facilitate this. A faction changed of 180570 to prevent Alliance seeing interaction option(wheel) has been added.

**The Sylvanas Event**

This is the event that occurs at 8pm every evening.  Preceding this are reminders at 30, 15 and 5 minutes before the event starts by Darkcaller Yanka.  Upon starting, Sylvanas is summoned as the Banshee Queen and delivers her speech after which, wickerman embers are summoned around the wickerman (which give a buff) and Darkcaller Yanka starts dancing.  This lasts the night (until 6:00am presumably = 10hrs from 8pm) when the dancing stops and the embers despawn. 

banshee queen
hedecbansheequeen
hedecwickerman1

There are a few issues for this event concerning how it is triggered i.e. One way would be using creature ai scripts using the spawning of Darkcaller Yanka as a reference point(Hallow's End start) to summon Sylvanas, determine her speech timings/emotes/despawn and summoning/despawning of embers. This method wouldn't be exactly accurate with server time unless the start time of the event is adjusted each year.

For this PR the triggers for the festival will be using creature_ai_scripts using the event OOC timer trigger.  The event start time (Yanka spawn) has been changed to 7pm so this will be the reference point for the scripts.  The first notification for the start of the festival will be at 7.30 so a time entry of 30_60_1000 will be entered for this first action. The repeat duration will be every 24 hrs or 24hrs_60min_60sec*1000=86400000. To list some other durations that are in the scripts will make this a little clearer.
1/2 hr = 1800000 ms
45mins = 2700000 ms
55mins = 3300000 ms
1 hr   = 3600000 ms
10hrs  = 36000000 ms
24hrs  = 86400000 ms

I'm not sure how to accomplish activating/deactivating the wickerman (set on fire/dousing) or summoning the wickerman ember gameobjects with db_scripts which is the other issue I would like to raise with this PR.

The other way to trigger this would be using a timestamp which would guarantee a more accurate spawns/despawns for the event as a whole.  I'm not sure which method is blizzlike and would appreciate some feedback on this matter. Maybe implementing this using sd2 would be a better solution.  The proposed db solution is problemtaic when the server is shutdown during the event with spawns event timings falling out of sync with the game.  A sd2 solution with timestamps would prevent this.

**Wickerman Embers**

To implement the spawn of the wickerman embers at the end of Sylvanas’ speech, a separate event was added to the game_event table.   This was the only way I could find to spawn/despawn gameobjects at a set interval.  Dbscripts didn’t seem to offer a way to do this and the only other way would be through sd2 which still may be the best way.  These embers spawn when the wickerman is lit and despawn when night finishes (which should be at 6:00am).  This is repeated daily throughout the event.
wickerman ashes

**Pumpkin Bags**

These are 16 slot bags which drop during Hallow's End from npcs that would normally drop the Traveler's Backpacks.  There are two conflicting entries which state these bags drop instead of/as well as the backbacks so I'm unsure of which version to implement.  The two entries are as follows:

This is the implementation for the pumpkin bags dropping as well as the backpacks.  

Finally, the apple bobs used during this event are not working and despite all efforts I was not able to find the cause for this.

### CODE REVIEW

**Comment by cala** [comment]
Thank you ! Impressive work, as usual. :+1: 
And as usual, expect some delay in the review for it. :tongue:

**Comment by cala** [comment]
I had a _very_ quick look at that PR.

There seems to be a great amount of work put in here!

My first remarks are about the use of AI scripts in numerous place.
- for the guardians, you use a mix of AI scripts (on spawn) and DB scripts (on death): either use AI scripts for both, or move the on spawn effect to an aura in creature_addon_template
- you use AI scripts for scripted texts on a timer, I think it would be preferable to use DB scripts for that purposes

I may have other remarks, but as I said I only had a quick look at your work. Sorry about that: I have already a lot of things on my plate and my limited knowledge/memory of this event requires me to do a bit of research to understand better your work.

**Comment by Zingzah** [comment]
Thanks for the look Cala.  I'll investigate tidying this part of the PR.  I'm still not sure db is the best way to implement some of the events.  I've had trouble finding how to spawn/despawn and activate objects through dbscripts.

**Comment by cala** [comment]
To spawn GOs via DB, there are two ways:
- add an entry in the `gameobject` table for the GO with a negative spawntime value (the value being the number of seconds before the summoned GO despawned) and you can spawn it with the DB command 9 RESPAWN_GAMEOBJECT
- use the spell that summons that GO if it does exists, for example Wickerman Guardian Embers (GO 180574) can be summoned by spell 25007 (Wickerman Guardian Ember)

There are a few commands in the [DbScript wiki page](https://github.com/cmangos/issues/wiki/DBscripts) related to GOs that you may find useful too. :smile:

**Comment by Zingzah** [comment]
Just added the changes for the Wickerman Guardians.  I also have a quick question about using dbscripts for spawning/activating GO.  I'm assuming the only table that would be appropriate for this is the dbscript_on_event table.  I've had trouble understanding how this table works exactly.  Is the id column an arbitrary value or connected to another table?  Spell and GO used as triggers aren't applicable in this as there aren't spell/GO types as described in the wiki involved and all there is left to work with is taxi(script?) waypoints.  The Npcs involved are stationary so I'm not sure exactly how to trigger this spawn using dbscripts and what would be blizzlike to do so.  Setting scripts at waypoint 1 for an involved npc seems like a hack solution.

**Comment by Zingzah** [comment]
Have been doing a some research on this and it appears this is actually how this is done with other NPCs in the db, not a hack at all lol.  I'll post some more changes with the conversion to dbscripts shortly.

**Comment by cala** [comment]
Sorry, I thought to have confirm this to you before: yes, it is the usual way to script non moving NPCs via DB scripts.

**Comment by cala** [comment]
And I commit myself to have this merged before the event starts this year. ;-)

**Comment by Zingzah** [comment]
lol Cala.  I've almost finalised the scripts to post.  I just wanted to run through what I'm proposing for Darkcaller Yanka.  This NPC announces the starting of the festival at 7.30, 7.45 and 7.55 each night of the event and the start of the event at 8pm.  I'm thinking the only way to accomplish this is to script Yanka through sd2 to do these actions and also summon the Banshee Queen according to server time.  Dbscripts only uses delay to time scripts and if the server goes down during the event, then whenever itcomes up again and Yanka respawns the festival will be out of sync.  So I'm attempting to write an sd2 script to trigger these actions with server timestamps.

**Comment by Zingzah** [comment]
Just adding all of the corrections I've made to date.  They address the Wickerman festival exclusively and include:
- converting creature ai scripts for Darkcaller Yanka and the Banshee Queen to dbscripts
- adding a script to handle festival announcements, summoning Banshee Queen, ignite/put-out Wickerman and trigger Yanka dancing
- removed wickerman embers as a separate event.  These should/will be spawned/despawned with script (sd2). 

I've used sd2 to handle this event to account for the server being started mid-event, which would be problematic with dbscripts alone.  Dbscripts are unable to  set a variable delay for actions and so if the server were started within the event then festival actions would be out of sync and incorrect. The wickerman embers spawning/despawning are the remaining functionality that needs to be added.  My time has been limited to work on this and I'm new to scripting which has delayed the addition of this feature.  

The equipment for Yanka and the Banshee Queen has also been atttempted to be added.  I understand from recent db commits that the creature equipment tables for classic are being reworked and I wasn't sure on how to be implement this.  I also don't have an accurate reference for the raw equipment table so I used the little information I could find to guess the right entries.  Darkcaller Yanka should hold her weapon in hand during the day and sheathed while dancing (pictured below).  The Banshee Queen according to the provided video above should be in hand during her speech.

I've arbitrarily place the script in the Tirisfal Glades file.  Let me know if this needs to be in a more appropriate section.
57162-darkcaller-yanka
57282-darkcaller-yanka

**Comment by cala** [comment]
It has begun... https://github.com/classicdb/database/commit/e0ae73ee2032cda4fad6ffa525a087cefa910b02

**Comment by cala** [comment]
Ok, I've started looking at this, so be ready for lots of questions. :wink: 

First one, regarding the Wickerman Guardians. Why did you move their disease aura from AI scripts to addon? They already have an AI script, so leaving it there would have been more suitable in my opinion.

**Comment by Zingzah** [comment]
I chose to do this from your earlier comment - 

"for the guardians, you use a mix of AI scripts (on spawn) and DB scripts (on death): either use AI scripts for both, or move the on spawn effect to an aura in creature_addon_template"

I thought that was what you wanted.  I understand the thinking is that creature ai scripts are for encounters and repeated actions whereas dbscripts are used for more simpler, once off - permanent actions.  For cases like the lolly quests where npcs react to a specific emote then creature ai scripts are the only option that provides this functionality.  If you're ok leaving the original implementation for the guardians as-is, that's ok by me.  As for the other earlier comments on both Yanka and The Banshee Queen - 

"you use AI scripts for scripted texts on a timer, I think it would be preferable to use DB scripts for that purposes"

The last additions I posted should have satisfied that.  I also decided to use sd2 for triggering festival announcements, igniting/dousing the wickerman and activating deactivating Yanka's dance because I couldn't find a way to do this with dbscripts or ai scripts.  If the server is shutdown/restarted at anytime during the festival, actions would be out of sync with server time due to fact that timed scripts use creature spawn as a starting time for any delays.  I still have to add embers spawn with sd2 if the current script is acceptable.

**Comment by cala** [comment]
> "for the guardians, you use a mix of AI scripts (on spawn) and DB scripts (on death): either use AI scripts for both, or move the on spawn effect to an aura in creature_addon_template"
> 
> I thought that was what you wanted.

My apologies, I was unclear and I did not look if the NPCs already had a AI script at that time. If you are OK with this, I'll move the on spawn and on death scripts to ACID so all will be gathered in one place.
Sorry.

**Comment by Zingzah** [comment]
No problems Cala.  Please proceed at your convenience.

**Comment by dagochen** [comment]
Missing? http://wowwiki.wikia.com/wiki/Katrina_Shimmerstar

**Comment by dagochen** [comment]
Apple Bobs are working for me now. 

INSERT INTO `dbscripts_on_go_template_use` (`id`, `delay`, `command`, `datalong`, `datalong2`, `buddy_entry`, `search_radius`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `comments`)
VALUES('180523', '0', '17', '20516', '5', '0', '5', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'Applebobs');

**Comment by Zingzah** [comment]
Thanks for the spot on Katrina Dagochen.  Corrections have just been added, which will fix a few problems relating to this one.  As far as your Apple Bob solution, it does add the missing functionality but the Apple Bob GO is a chest. It should have an opening time and present the apples as loot like a regular chest does.  I just can't identify where the disconnect is in this case.  It will probably something very obvious and simple and I will have to /facepalm myself.

**Comment by dagochen** [comment]
There is also missing Rachelle Gothena <Hallow's End Treats> in Orgrimmar I guess.

The problem with the chest is, that the Client sends a CMSG_GOBJ_USE which does not result in a castbar or so. You have 2 options in this case: 
- SD2 Script
- dbscript_on_go_template_use (or - dbscript_on_go_use, which is for each single go, so I wont recommend that)

Maybe you can make a dbscript which makes the player cast an opening spell on the go. After the cast time is finished you can use my dbscript from above to reward the item to the player?

**Comment by cala** [comment]
The aura for Wickerman Guardian was added in this [ACID commit](https://github.com/ACID-Scripts/Classic/commit/1383446b65fc53677f3bed0543879c50219198ec). :+1: 

Regarding the Sylvannas event, SD2 is indeed a valid approach. However, there is a [PR open in core](https://github.com/cmangos/mangos-tbc/pull/71) that could allow us to do this in a more convenient way. @Phatcat is currently reviewing it and if this is merged, we will see how the Sylvannas event can use it.

**Comment by dagochen** [comment]
Some bugs I could find so far:
- quest 1657 is not possible to finish. After using 3 stinky bombs and having 3/3 the questlog says its done, but yanka does not.
  FIX: UPDATE quest_template SET SpecialFlags = 0 WHERE entry = 1657;
- Seargant Hartman does not engage in pvp, though he probably should (military rank+being part of the event, so he should fight horde like the usual guards do)
- yanka and hartman should be only visible during event and need to be added to game_event_creatures table
  FIX: INSERT INTO game_event_creature(guid, event) values (160015, 12);
  FIX: INSERT INTO game_event_creature(guid, event) values (160014, 12);

**Comment by dagochen** [comment]
INSERT INTO `dbscripts_on_creature_death` (`id`, `delay`, `command`, `datalong`, `datalong2`, `buddy_entry`, `search_radius`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `comments`) VALUES (15195, 1, 15, 27005, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Wickerman Guardian Ember');

Spell 27005 does not exist or am I wrong?

**Comment by Phatcat** [comment]
https://github.com/cmangos/issues/issues/19

**Comment by dagochen** [comment]
You might wanna tell us whats the point in the issue you linked us here @Phatcat ....I'll bet nobody knows what to do with that....?

**Comment by Phatcat** [comment]
... It's an item relating to the hallow's end and in direct relating to Apple bobs (bobbing apple / apple bobs .... comeon, man)

This is your words:

> Apple Bobs are working for me now. 

Furthermore, I am getting a bit tired of your attitude towards me dagochen.

**Comment by dagochen** [comment]
2016-09-15 01:58:10  DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 1519301, command 9 failed for gameobject(guid: 37875, buddyEntry: 0).
2016-09-15 01:58:10  DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 1519301, command 9 failed for gameobject(guid: 37876, buddyEntry: 0).
2016-09-15 01:58:10  DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 1519301, command 9 failed for gameobject(guid: 37877, buddyEntry: 0).
2016-09-15 01:58:10  DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 1519301, command 9 failed for gameobject(guid: 37878, buddyEntry: 0).
2016-09-15 01:58:10  DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 1519301, command 9 failed for gameobject(guid: 37886, buddyEntry: 0).
2016-09-15 01:58:10  DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 1519301, command 9 failed for gameobject(guid: 37887, buddyEntry: 0).

The wickerman ember objects exist, are not spawned (spawntimesecs = -360000) and can not be accessed in any way. I also tried some sd2 script, but even with GetClosestGameObjectWithEntry() they can not be found. If I switch the spawntimesecs to something positive, they are always spawned. Any ideas?

**Comment by dagochen** [comment]
@Zingzah @cala Go Go guys ;) only 1 Month remaining!

**Comment by Zingzah** [comment]
So as far as the Wickerman Embers GO's Dago, I was waiting for the commit Cala mentioned earlier.  I would understand now that there is the  ability to link events (thanks guys to all involved for latest commit), that the embers can be entered in a separate event and linked to the Hallow's End event.  I was originally trying to accomplish this with sd2 but this way would be much simpler.  I'll be testing this with the new changes to see how it works out.  I'm not sure how the other actions (Festival announcements, Wickerman igniting, Yanka dancing and summoning the Banshee Queen) can be triggered with this change and not use sd2 altogether or whether there will still need to be some component of sd2 used.  First things first will be to spawn/despawn embers with this latest addition.

**Comment by cala** [comment]
The change was added to core in https://github.com/cmangos/mangos-classic/commit/b084f64d44342e75fd49f477bd677003cecebc20
And to Classic DB in https://github.com/classicdb/database/commit/29691eb7bc8eb5a48502c50595fe4fa163a32d94
I think all that is related to the Banshee Queen event could also be done with that addition and the help of a few tricks.
For example, one can imagine a trigger NPC (invisible) spawned by subevents at the correct hour each day the Hallow Ends. This NPC could have a dbscripts_on_movement that use Yanka or the Banshee Queen or whatever as buddy. Just an idea.

**Comment by cala** [comment]
@Zingzah I'm about to push the Pumpkin bags part and I only saw source where it drops from mobs, not from gameobjects like chest. Are you sure of that part, please?

**Comment by Zingzah** [comment]
Ok, for this I did a bit of deduction so you might not agree with my reasoning.  From the reference:
http://web.archive.org/web/20061129092910/http://www.wowwiki.com/Hallow%2527s_End
I thought to look for all sources of the traveler's backpack and assume that the Pumpkin Bags would also replace the loot tables of the chests listed here:
http://www.wowhead.com/item=4500/travelers-backpack#contained-in-object
I couldn't find any direct references of pumpkin bags looted from these chests so I'll leave the decision to you whether you think Pumpkin bags would replace the Traveler's Backpack from this type of source.  Go ahead with whatever you think is most authentic. :)

**Comment by cala** [comment]
Ok, thank you for the explanation. :+1: 
In doubt, I removed the chest part. The item is now added in https://github.com/classicdb/database/commit/46086bc35f3407af01cd71a6d2a43eaa60f6e1f1

I have another question (I told you there would ne many of them) ;)
Regarding the quest where player has to do emote to NPCs to complete quest. From what I understand, as you did it with ACID, the NPCs will react everytime the emote is performed, even when Hallow's End is not active. Is that right?

**Comment by Zingzah** [comment]
So for each of the innkeepers that are involved, a creature_ai script  has been made containing an event receive emote entry.  A condition attached to each of these entries is that the player must be on the corresponding lolly quest of that particular innkeeper for the emote to trigger a response. As such any player not on the correct quest will not receive a return emote from the innkeeper. Also as long as you have the quests in your log you the Hallow's End event doesn't have to be active to complete them as well.

From http://www.wowhead.com/quest=8311/hallows-end-treats-for-jesper#comments

By Akamadoushi (3,147 – 7·77) on 2010/11/07 (Patch 4.0.1)  
I picked up this quest during Hallow's End but kind of forgot to finish it in time. Interestingly enough, I was still able to pick up and complete all of the four sub-quests and receive the treats today (6th November), but I can't turn the quest in because Jesper isn't at the orphanage anymore (as was to be expected, given that he's a seasonal NPC). I can still "see" him as a question mark on the minimap, though.

Now, I wonder if I should bother to keep all the candies for one year... :P
Last edited by Akamadoushi on 2010/11/07 (Patch 4.0.1)

3

rowaasr13 on 2011/11/02 (Patch 4.2.2)
It still works same way in 2011. As long as it is in your log, you have all 4 sub-quests available and can impress bystanders by making innkeepers wish you "happy hallow's end" all year around.

I hope this clears up that issue for you.

As a side note, the orphans carrying spears in orgrimmar orphanage will be corrected in a future PR for Children's Week.  Hopefully they don't put out anyone's eye until then. :)

**Review by dagochen — CHANGES_REQUESTED** [review]
Add the other NPC in Orgrimmar as well.

**Comment by Zingzah** [comment]
Just pointing out a minor correction needed for the pumpkin bag commit identified by katz
katz1 10 hours ago

@cala
@Zingzah

The installer script gives me:
ERROR 1054 (42S22) at line 5: Unknown column 'entry' in 'where clause'

+-- Added drops for item 20400 (Pumpkin Bag) that should only drop for Hallow's End
+
+SET @CONDITION := 162;
+
+DELETE FROM `conditions` WHERE `entry` = @CONDITION;

Last line needs to be changed to:

+DELETE FROM `conditions` WHERE `condition_entry` = @CONDITION;

should fix the problem

**Comment by cala** [comment]
The Lolly quest part is partially fixed in https://github.com/classicdb/database/commit/11fdf818663ed31dbb598aa6fb7aec5d25c8d8bf
The AI part will be pushed to ACID soon. I did not see the conditions for the EVENT_RECEIVE_EMOTE, sorry.

From what I read, these scripts also need to be pushed to TBC and WotLK branches, am I right?

**Comment by dagochen** [comment]
Didn't the event changed from 2006 to 2007/2008/...?

**Comment by Zingzah** [comment]
Yes that's right.  The Jesper and Spoops quests are the only quests that have endured the event right up until the current incarnation.  So they are in TBC and Wotlk as well.  The event did change in TBC and Wotlk Dago, the main one being the addition of the Headless Horseman events in Scarlet Monastery, questline and Shade of the Horsemen events in starting zones.

**Comment by cala** [comment]
[ACID scripts](https://github.com/ACID-Scripts/Classic/commit/eadcee90f1fcc4eb5b8aa2d2463279ac9d85a621) for the Lolly quests are now up.

**Comment by cala** [comment]
Wickerman Festival in https://github.com/classicdb/database/commit/d7e037e041262938c6f76b7b2b158a724e036568

**Comment by cala** [comment]
Stinking quests (Alliance+Horde) in https://github.com/classicdb/database/commit/c0eae8245fe0b37a228939586aa8f4118af19f1a
Remains to be done: Banshee Queen event

**Comment by Zingzah** [comment]
Phew! Thanks for all of that Cala,  We're almost there....

**Comment by cala** [comment]
@Zingzah I see that you make Darkcaller Yanka unattackable. Are you sure about this?

**Comment by Zingzah** [comment]
Absolutely unsure Cala.  I'm not aware of what the usual policy was for event NPCs and I can't ever recall whether they were attackable or not.  It's something I'm going to have to observe in current events to see what they have in place.  So if you believe Yanka should be attackable then I trust your experience/judgement in this case.  Probably the case for Sargeant Hart as well.

**Comment by Phatcat** [comment]
You guys probably already seen these but just in case;
(2005 event)
https://www.youtube.com/watch?v=0RH8dhS2D3U

(2006 event)
https://www.youtube.com/watch?v=Eus8SaiwDWE
https://www.youtube.com/watch?v=VlvxGonap2E
https://www.youtube.com/watch?v=AbzFttf3GZU

(2007 event - probably not too much interesting in these applies to classic, I know the whole horseman thing don't)
https://www.youtube.com/watch?v=IbMm7sPdUaM
https://www.youtube.com/watch?v=kjWIz698kks
https://www.youtube.com/watch?v=HjePUKW-xFg
https://www.youtube.com/watch?v=qxh7He9ZamE

**Comment by cala** [comment]
Completed and closed by https://github.com/classicdb/database/commit/5df7f7c28debfc8b5660e796505ef36c16b4a0bc without the use of SD2 or ACID.
Thanks very much @Zingzah and for every other contributor and feedback! :+1:

**Pull request closed without merging**
