### PR TITLE
Winter Veil Fixes 2

### PR DESCRIPTION
**Pull request by Zingzah**
This is the second pass at the Winter Veil event.  It will hopefully cover the majority of the remaining database problems I found.  I also found a few spell problems that require some core work which aren't covered in this PR. 

This PR does address the following issues:
1.  The christmas companions were not working and required a simple change in the DB to the working spell in the core. The helper box companions when summoned were also the incorrect scale so this has been adjusted for both helpers.
2.  The Wondervolt Trap radius was too large with players being transformed before even reaching the Wondervolt pad.  The radius has been reduced so that players must be more or less in the centre of the pad to be transformed.
3.  From the previous changes, Goli ended up in a very cold and isolated place with no friends or ale closeby to get acquainted with.  A minus sign along with Goli's correct position have been restored.
4.  An NPC (Winter Helper(gm)) was missing from the DB causing players to be incorrectly transformed into a porcine version of themselves via spell 26157.  The NPC has been added and players will now transform correctly.  An extra Winter helper model was added to npc 15835 which had one less than the other helpers. 
5.  Menethil and Gadgetzan folk were crying afoul as their Wondervolt machines and operators were noticeably absent.  This quashed any plans for the Gadgetzan Waterworks Company "Christmas Gnomebilations" and Deepwater Tavern's "Kiss me you burning hunk of Gnome" Christmas events.  The machines and operators have been restored saving both of these Azerothian "must do" events. A special thanks to Evil@wow for DB info on the Wondervolt stations which was very hard to come by.  Screenshots shown in https://www.flickr.com/photos/afkgamer/sets/72157603469285495/.  http://www.engadget.com/gallery/winter-veil-2007/#slide=912879 Shows the present placement although I found it hard to get the placement exactly.  Perhaps someone might have exact coords in a sniff log somewhere.
6. All wondervolt machines (including the newly added ones) have had their snowclouds restored.  Wondervolt machines without snowclouds are like trolls without fangs.  Very sad indeed.
7. Alterac Valley hijinxes have been restored by adding the Hardpacked Snowball to the DB and the Hardpacked Snowdrift loot table.

### CODE REVIEW

**Comment by cala** [comment]
Thank you. :+1: 
I'll review this soon.
As a side note, I had already fixed the position of NPC Goli in your previous PR (he was effectively very alone).

**Comment by Zingzah** [comment]
This NPC(15710) is one of the companion pets from the Winters Veil event.  According to

http://www.wowwiki.com/Snowman_Kit
http://www.wowhead.com/npc=15710/tiny-snowman#comments and 
http://www.wowhead.com/spell=26045/tiny-snowman#comments

this companion pet does not move after summoning and mirrors some emotes (dance, wave, kiss, bow).
Currently this pet follows the player when summoned (summoning is possible after Winter Veil Fixes 2 is applied to DB)
and does not mirror any emotes.

This Tiny Snowman DB fix will stop the companion following once summoned and will mirror 4 different emotes when targeted.
Emotes supported are /dance, /wave, /talk and /talkex.  These were the only animations that were available when viewing the snowman
model through the modelviewer.  Perhaps the /kiss and /bow emotes were added in later expansions.

I'm still not sure how to exclude my updating merges from PR's so ignore the merge commit.

**Comment by evil-at-wow** [comment]
> I'm still not sure how to exclude my updating merges from PR's so ignore the merge commit.

I believe you can't. It's a github 'feature': once you have opened a PR for a branch in your repository, **all** subsequent commits in that branch will automatically be added to the PR.

So if you don't want these, you have to use separate branches in your repositories.

**Comment by Schmoozerd** [comment]
This is actually a reasonable "best practice": Use (feature) branches:
One branch for each feature (containing 1-multiple commits)

**Comment by Zingzah** [comment]
Thanks for the advice.  Been wrestling with github and slowly working things out.  I will try some things based on the advice given.

**Comment by cala** [comment]
In https://github.com/classicdb/database/commit/2d87aeb4c683c88891bb793d9f4d773899644517 
thank you. :+1: 
The EventAI part will be pushed to ACID repo.

**Pull request closed without merging**
