### PR TITLE
[] - Temple of Ahn'Qiraji - Changes to GOs

### PR DESCRIPTION
**Pull request by Tobschinski**
- locked the large scarab coffers
- idols in coffers are now lootable without being on a certain quest
- corrected the rotation of doors and coffers

### CODE REVIEW

**Comment by cala** [comment]
Thanks for this pull request. I did not look yet at the current DB state, but I notice that you update the rotation of every GO in AQ40, not only doors or coffers. Is this really intended?

**Comment by Tobschinski** [comment]
Oh, it is. However, updating the grasps and the sandpile or whatever this thing at Viscidus may be called is optional, as they are rounded and due to that, not affected if one changes their rotation.

Since the rotation of coffers and doors are false and the positioning comes only from their coordinates, I didn't mind updating every GO, because I would consider them as false as well.

Let me know if you do not want to have things happen, I will change it asap.

**Comment by cala** [comment]
I understand your point and you are right, the query will have no side effects as it is.
It is always advisable to avoid using the evil GUIDs in a query, like you did here. However, with such a generic where clause, one can not be sure of what the query will do without checking first the DB, like you did.
This is why it is preferable to have more specific where clauses (also using GO entries in this case, for instance). It makes the code more easily understandable and portable to other friendly DB-projects.

**Comment by cala** [comment]
Accepted, thank you.

**Pull request closed without merging**
