### PR TITLE
[] - Temple of Ahn'Qiraj - Changes to Wasp-Packs

### PR DESCRIPTION
**Pull request by Tobschinski**
- updated stats
- updated minlevel of Vekniss Warrior
- linked creatures to bosses
- added Qiraji Lasher
- pooled Qiraji Lasher / Vekniss Wasps
- removed not needed creatures

### CODE REVIEW

**Comment by Tobschinski** [comment]
There are still a lot of things to do for the related creatures.

There are still missing way-points for Vekniss Stinger, Hive Crawler and Warrior. I'd like to do it once I got a working parser.
However, if you want to have some basic ones, let me know, I'll try to let them move at least somehow.

All related creatures will need to be moved as well.

Since the chaining of creature_linking is broken, I did not add add linking within groups, just to the bosses. When it is fixed, we can simply add it to override the template and have the wanted spawn-behavior.

The respawn-time is still untouched, I need to get the ones from retail.

~~Reputation needs to be changed.~~

**Comment by Tobschinski** [comment]
With lots of related things to do, you may wanna stall this commitment.

**Comment by cala** [comment]
Sorry, I took my time to answer to this PR.

As always, thank you for submitting this.

Regarding the movement path, it all depends on the time it will take to get the waypoints. If you think you can get a reliable parser soon, then wait for them. On the opposite, if you are unsure of it, better use waypoints added manually (if errors are not really noticeable and if this is not too much work for you).

I agree with your suggestion to stall this commit, waiting for the above mentioned updates. I still intend to add it in the next release.

**Comment by Tobschinski** [comment]
no longer needed

**Comment by cala** [comment]
All the content from this PR was moved to the new one?

**Comment by Tobschinski** [comment]
Nope, I threw pretty much everything in here I mentioned, the new ones will be more structured and of course provide more content..

**Comment by cala** [comment]
Ok. Thank you for clarifying. :)

**Pull request closed without merging**
