### PR TITLE
Instance spawn positions

### PR DESCRIPTION
**Pull request by Phatcat**
https://github.com/classicdb/database/issues/856

To be improved:

Have wrong height:
- Razorfen Kraul - both enter and exit
- Entering Blackrock Depths spawns in the air, leaving seems good.
- leaving Blackrock Spire.
- Leaving scholomance

Have wrong orientation:
- The orientation leaving Dire Maul East is clearly off

May have wrong orentation:
- Shadowfang keep - both entering and exiting
- Dire Maul West - Entering
- Dire Maul North - Entering
- The orientation leaving AQ20 seems very off.

---

This change is [Reviewable](https://reviewable.io/reviews/classicdb/database/888)

### CODE REVIEW

**Comment by cala** [comment]
Nice. :+1: 
If you are confident with those positions, feel free to merge it and even fix the names that are wrongly written like Blackfathom.

**Comment by Phatcat** [comment]
Well, I think the fact that the position on all of these is spot on and should tell us that they may at least be very close to the original values. However; those that have the wrong height need to be sorted, as well as the one with the clearly wrong orientation; (DM east) - the rest I'd say _seem_ acceptable.

I really would like a second opinion on these.

I'll add in some name changes, notably clean up in all those instances misspelled or those instances with several entrances that seem to share their name in the db (I am looking at you in particular DM)

**Comment by cala** [comment]
Alright, I'll test all of them when I can spare the time.
Aside from a few quick updates here and then, I committed myself to the Hallow End event PR here before. ;)

**Comment by Phatcat** [comment]
I'll update the commit with name changes for the area triggers (can I also do some of the other name changes I talked about?) and add it to my todo list that tables such as target position could do with a name/comment field (initiated from core side)

**Comment by Phatcat** [comment]
Those with the wrong height my suggestion is to use the transport, then wait until my char drops down, being careful not to move nor rotate, and then get my current location and correct the 'z' position in in those? Otherwise people are gonna be dropping down from the air during those cases I reported here on this PR.

Those that 'may' have wrong orientation I think we should ignore for now, maybe open an issue ticket about. More importantly though, are those cases we still have not gotten data on (by the way, once again thanks @evil-at-wow)

**Comment by evil-at-wow** [comment]
No problem! I haven't had the chance to look through some more sniff data yet and see if I can find some of the ones that are still missing, but I will do so one of these weeks. 

I'll also see if I can figure out why some data is not matching Classic and TBC. I quickly tested the RFK ones I posted with my TBC server and they are indeed quite wrong. Yet I can't imagine that the relevant world/dungeon geometry changed so much from TBC to WoTLK, so I suspect something else is going on...

**Comment by Phatcat** [comment]
I went ahead and updated the names as well, but I am not gonna move on this until we find out what is the cause of those current issues with the sniffed data

**Comment by cala** [comment]
Ok. Next on my list.

**Comment by cala** [comment]
Done. I confirm you remarks above. However: 

> May have wrong orentation:
> 
> -Shadowfang keep - both entering and exiting
> - Dire Maul West - Entering
> - Dire Maul North - Entering
> - The orientation leaving AQ20 seems very off

I'm not sure the orientation is wrong in those cases. Yes, the player's orientation is not parallel to the normal of the instance portal, however, player is oriented in the direction he will follow to move on (towards the instance or exit). So, I guess those are correct.

So, unless @evil-at-wow find that something is going on, I suggest that you either push that PR as it is, or push it after manually editing the teleport with a wrong Z-axis and the DM East with wrong orientation (it is set to 0.000 currently).

:+1:

**Comment by Phatcat** [comment]
alright so I tested the RFK ones against wotlk and indeed something is up because the geometry did not change, you also drop from the air using those values there, so... I have corrected the height so that you no longer drop anymore just by letting my char drop and updating the z-axis value accordingly.

I fixed the one orientation in Dire Maul, it is however exiting that was wrong, not entering; entering is the one with a 0 orientation and that one seems fine.

Given that these are an improvement, closer to retail than we had before no doubt, then I think we should merge it. We can always do corrections if more data appears.

**Comment by cala** [comment]
Agreed! :+1:

**Pull request closed without merging**
