### PR TITLE
[] - Molten Core - Changes to Firelord / Lava Annihilator

### PR DESCRIPTION
**Pull request by Tobschinski**
- added missing spawns
- pooled previously added and existing creatures
- fixed movement behavior

### CODE REVIEW

**Comment by cala** [comment]
Thanks for this update. I'm currently in the middle of updating the stats of about 9 thousands creatures, so it could be some time before I can properly review it. I will nonetheless spare some moment to write you a template script for the vekniss drones in AQ40 we previously discussed.

**Comment by Tobschinski** [comment]
On your own? Let me know if you need some help. I do not even mind the most tedious work. : /

**Comment by cala** [comment]
As usual, just to be sure to understand what you are doing here:
- you remove all firelords/lava annihilators
- you spawn new ones (based on retail?)
- you respawn previous ones (too many to update, delete/insert was quickier?)
- you group them in pools (1 annihilator, 1 firelord, 50% each)

Am I right ? If so, sounds good. :)

**Comment by Tobschinski** [comment]
Yep!

50% is just an assumption, my only info is that they 'share' their spawn-point. Chances may be slightly different.

**Comment by cala** [comment]
Just to get your thought on this. I'm thinking of increasing the spawndist to 5 (and even slightly more) because a spawndist of 2 for such large creatures is non sense.

**Comment by Tobschinski** [comment]
Well, they are not really supposed to walk around, they should just turn around a bit and do some little steps here and there.
I will see if I can get any better value out of retail.

**Comment by Tobschinski** [comment]
Here, https://www.youtube.com/watch?v=R_w_EjTzIxs#t=533, you can see a player running towards 3 Firelords. Maybe you can get a better value out of this video.

**Comment by cala** [comment]
Accepted, thank you.

**Pull request closed without merging**
