### PR TITLE
Correcting Loot of Rare Mobs in multiple zones

### PR DESCRIPTION
**Pull request by Sinoxan**
*Elwynn Forest
*Westfall
*Redridge Mountains
*Duskwood

*Creature IDs:
*61, 79, 99, 100, 462, 471, 472, 503, 506, 507
*519, 520, 521, 534, 572, 573, 574, 584, 947, 771, 1424

*Adding in Loot to some mobs
*Removing Unique Loot from Reference Tables
*Adding Unique Loot to different group
*Correcting Drop Rate to sum to 100%

Source WayBack Machine Allakhazam

### CODE REVIEW

**Comment by cala** [comment]
Thank you for this pull request. I will need some time to review it as my todo list is quite long at the moment. ;)

**Comment by PatSmuk** [comment]
`UPDATE x SET y TO z;`
Is not standard SQL. Please use:
`UPDATE x SET y = z;`

Docs:
http://www.postgresql.org/docs/9.1/static/sql-update.html
http://www.sqlite.org/lang_update.html

**Comment by Sinoxan** [comment]
@Patman64 Changed it and updated the file naming as well

**Comment by cala** [comment]
Accepted, thank you.

**Pull request closed without merging**
