### PR TITLE
Stratholme - Changes to Plague Ghouls & Skul (living side) 

### PR DESCRIPTION
**Pull request by Tobschinski**
- added movement
- fixed movement-speed
- removed not needed spawns (static spawns are untouched)

### CODE REVIEW

**Comment by Tobschinski** [comment]
the one blocking the skul rare spawn is missing, i will add it asap

**Comment by cala** [comment]
Does this mean that it is preferable that I wait before merging this?

**Comment by Tobschinski** [comment]
I don't know. This ghoul does not really matter right now, as Skul is
missing anyway.
I do not even know if it should be there in vanilla, tbc and wotlk. (Skul should be) A few
groups have been removed during the overhaul. Maybe some have been added.

To be sure, I'll need to watch more videos.

**Comment by evil-at-wow** [comment]
Not relevant for this particular issue, but just to share info: at least for the undead side, [this](http://www.blizzardguides.com/images/gauntlet.jpg) map is accurate for Classic because it was made during Classic (April 2006 I believe).

**Comment by Tobschinski** [comment]
I am talking about this one:
skulblock

---

> Not relevant for this particular issue, but just to share info: at least for the undead side, this map is accurate for Classic because it was made during Classic (April 2006 I believe).

Thanks, every piece of information is appreciated. I wondered if there has ever been a group containing humanoids and undeads. (The one next to the Baroness.) Now I have my answer.

**Comment by cala** [comment]
That is a precious map then. Thanks ! :)

**Comment by Tobschinski** [comment]
Damn, I am a bloody git-amateur.

However, this PR is ready to be reviewed, I think.

**Comment by evil-at-wow** [comment]
That screenshot is pretty useful because it's now perfectly clear which one you mean! 

I have Stratholme data from a few runs done early WoTLK (patches 3.0.3 and 3.1.3). It's not exactly Classic, but at least I should be able to answer your question for WoTLK. I'll parse the data one of these days and post the result.

**Comment by cala** [comment]
Accepted, thank you.

**Comment by evil-at-wow** [comment]
I parsed some Stratholme data (version 3.0.3 build 9183) and I can confirm that the Plague Ghoul in your screenshot was present. Well, at least there was a lonely spawn close to that position:

> GUID 0xf1300028a50073fa: Entry = 10405 (Plague Ghoul), Position (x y z o) = 3480.51 -3317.26 130.894 4.31926.

**Pull request closed without merging**
