### PR TITLE
[] - Ruins of Ahn'Qiraj - Changes to Hive'Zara Wasp #1

### PR DESCRIPTION
**Pull request by Tobschinski**
- added correct number of groups
- changed position
- linked to hive'zara stinger
- removed hive'zara hornets as a permanent spawn (-> Ayamiss encounter)

### CODE REVIEW

**Comment by Tobschinski** [comment]
Part (3/3) of https://github.com/classicdb/database/issues/427

**Comment by cala** [comment]
A PR that also closes an issue? Nice ! Thanks for submitting this. :+1: 

Regarding the linking, I assume the wasps are linked by group of 2 NPCs to the nearest stinger? If so, it would be better to link them by creature_linking_template with a radius value > 0

**Comment by Tobschinski** [comment]
> A PR that also closes an issue? Nice ! Thanks for submitting this. 

:)

> Regarding the linking, I assume the wasps are linked by group of 2 NPCs
> to the nearest stinger? If so, it would be better to link them by
> creature_linking_template with a radius value > 0

If nothing odd will happen due to the different composition at Ayamiss,
sure, why not.

**Comment by cala** [comment]
Accepted, thank you.

**Pull request closed without merging**
