### PR TITLE
[] - Temple of Ahn'Qiraji - Changes to Qiraji Slayer / Mindslayer

### PR DESCRIPTION
**Pull request by Tobschinski**
- Position (Formation)
- Reputation
- Stats, Respawn
- Linking
- Pooling

### CODE REVIEW

**Comment by Tobschinski** [comment]
Be careful with these, I have given you the option to decide which guid will be used, as I have not been able to find space for 64 creatures within the range of AQ40. (I will need another ~200 for other creatures anyway) The default used 590500 is way to high and should be changed.

The guids must not be splitted.

PS. This would have been a perfect situation for me to learn something about loops T_T

**Comment by cala** [comment]
Thanks. To be sure that I perfectly understand what is going on with the pools:
you are pulls for every mobs in every pack, allowing some variability in the pack composition. This will possibly result in some packs having 100% slayers or 100% mindslayers (unless you chose to fix some of the members in each pack, I did not check that)

Regarding the SQL code, I'm not sure that

``` sql
SET @ORIENTATION := (SELECT `ORIENTATION` FROM `creature` WHERE `guid`=@QWARRIOR);

SET @B := (SELECT(@DISTANCE * SIN(PI() / 2) / SIN(@ORIENTATION) * -1));
SET @C := (SELECT SQRT(POW(@B, 2) - POW(@DISTANCE,2)));
```

Is evaluated again every time @QWARRIOR is reaffected, meaning ORIENTATION, B and C will always be the same. I'm must check that also if this is OK for every SQL version.

**Comment by Tobschinski** [comment]
Yes, the packs after the Twins may consist of ANY combination of Slayers and Mindslayers. It is possible and wanted to get up to  4 Slayers or 4 Mindslayers.

You are right that each Qiraji Champion has the same orientation, because I did not change that in `creature` All of them have 4.86 so foar. I can change that to the orientation of the first waypoint if it is wanted. I thought it would not matter since they are supposed to patrol without having a break 
ever.

That's why `Orientation` is never changed and B & C remains the same.

**Comment by Tobschinski** [comment]
I will change this to have the needed parts only .

**Comment by cala** [comment]
Thank you for clarifying the pack composition (I honestly don't remember though I cleaned AQ many times in Classic).

> You are right that each Qiraji Champion has the same orientation, because I did not change that in creature All of them have 4.86 so foar. I can change that to the orientation of the first waypoint if it is wanted.

You can leave them as they are, as the NPCs are moving, their spawn orientation is usually irrelevant (but for a few exceptions).

Unless I'm mistaken, those packs are unique to the trashs after the Twins Emperors and as such, we do not find them in other configuration in the instance. If so, I think I will move the linking to `creature_linking_template` with a radius of the distance you used for spawning the NPCs around the warrior (let's increase it by 1 yard to avoid any bad rounding value)

**Comment by Tobschinski** [comment]
Oh cool, I didn't know that was possible.

I am glad  to not have to move them, I would have to check each `position_z` again to not make them fall through the ground :)

**Comment by cala** [comment]
I reviewed this PR yesterday, and I will probably push it this evening (GMT time) with a update of the linking (as mentionned above). I did not see any issue with the Z position of the Slayers/Mindslayers, but your check on this matter is welcome.

**Comment by Tobschinski** [comment]
Oh, not needed with the current positioning. 
A check would have been necessary if the orientation of the Qiraji Champion were changed.

**Comment by cala** [comment]
Accepted, thank you.

**Pull request closed without merging**
