### PR TITLE
Stones of Binding - small fix (issue #107)

### PR DESCRIPTION
**Pull request by Jaypy**
- Correct Values for the 'Stone of Binding' objects needed for the quest 'The Stones That Bind Us' (ID: 2681)

### CODE REVIEW

**Comment by Phatcat** [comment]
this repository is however no longer where you should open new issues or pull requests, this repository is in maintenance mode while we are moving towards using https://github.com/cmangos/classic-db (which is also where you should pr and open issues regarding ACID if that becomes relevant to you, since db and ACID have been merged)

I am unsure if it'll be needed for you to move these already open PRs, I'd think not, but for future reference you rather want to use the new repo (which is also the one you should work against, since this one most likely won't see any new commits)

**Comment by Jaypy** [comment]
Oh, for sure. Im assuming reopening them on the new repo is easier for the move?

**Comment by Jaypy** [comment]
I mean it would be easier for me to just let them be, so i dont have to do all this on a new fork :S

**Comment by Phatcat** [comment]
Yes, leave them be, it's minimal extra work pulling them in from here compared to directly on the other repo, I'm sure it'll be fine. Just. For future reference =)

**Comment by cala** [comment]
In https://github.com/cmangos/classic-db/commit/e2e1fb24a953c04f2cfda8ea9fc32da49569bf86, thank you! :+1:

**Pull request closed without merging**
