### PR TITLE
Stratholme - Changes to the Crimson Faction

### PR DESCRIPTION
**Pull request by Tobschinski**
- updated a few min and maxlevel based on the Bestiary (and other sources)
- updated the faction of every member

### CODE REVIEW

**Comment by Tobschinski** [comment]
I've seen that almost everywhere, in each dungeon or raid, faction 14 is used as a default faction.
Faction 14 will not fight the Scourge, like the Scarlet Crusade should. (the spawns in the Crusader's Square or the ones spawning after Balnazzar's death)

There are only 2 factions that are named Scarlet Crusade, # 67 and # 89. 
Unfortunately, I do not have sources to rely on, I've just taken the faction that the Crimson Courier is using.

Any info about this is appreciated.

With that, I've seen some necessary updates to some creature's level-range. (Bestiary)

**Comment by evil-at-wow** [comment]
When I parse my Stratholme data, I'll check what faction they have. I would assume they all share a faction, but I'll just check a few different types in the area where Timmy spawns and in the, urm, cathedral (or whatever it is).

**Comment by Tobschinski** [comment]
That'll be cool!

**Comment by cala** [comment]
Thanks for this pull request.
UDB has faction 67 for those creatures (except two who have faction 32 : wolf, but this is typically the case for untested NPCs). So, when reviewing this PR, I'll change the faction accordingly. :)

**Comment by evil-at-wow** [comment]
As promised, I parsed some Stratholme data (version 3.0.3 build 9183). Assuming the values in this version are matching the Classic values, I can confirm the UDB data is correct.

According to my parser, the value for UNIT_FIELD_FACTIONTEMPLATE is 0x00000043 (so 67 decimal) for all NPCs I checked, which is the following list:

| Entry | Name |
| --- | --- |
| 10418 | Crimson Guardsman |
| 10419 | Crimson Conjuror |
| 10420 | Crimson Initiate |
| 10421 | Crimson Defender |
| 10422 | Crimson Sorcerer |
| 10423 | Crimson Priest |
| 10424 | Crimson Gallant |
| 10425 | Crimson Battle Mage |
| 10426 | Crimson Inquisitor |
| 11043 | Crimson Monk |
| 11054 | Crimson Rifleman |
| 11120 | Crimson Hammersmith |

**Comment by cala** [comment]
Thank you @evil-at-wow for confirming this! :+1:

**Comment by cala** [comment]
Accepted, thank you!

**Pull request closed without merging**
