### PR TITLE
Corrected the droprate of Witchwing Talon

### PR DESCRIPTION
**Pull request by katz1**
Source: http://db.vanillagaming.org/?item=5064
Previously it was 39% for every related harpy.

### CODE REVIEW

**Comment by cala** [comment]
Thank you for your pull request.

Unfortunately, I have to disagree with that one.

The current drop rate may be wrong, but it seems at least to be OK with wowhead on that : http://www.wowhead.com/item=5064/witchwing-talon
The source you are using here is from a private server which is likely a fork of mangos or c-mangos.
As such, the DB is not reliable.
For example, 80% drop rate is the default value for quest items in Classic DB for items we don't know the proper drop rate. That just means that at some time, vanillagaming was built over what is now Classic DB and that they are still using the "default" drop rate for that item.

If you are feeling that the current drop rate in Classic DB is too low, I'd be happy to discuss this however.

**Comment by Phatcat** [comment]
The thing that can end up being really confusing when figuring out the actual drop rate for quest items when using values from ANY source WHATSOEVER is that there is no indication of how many of these kills happened with someone on the quest. Let's say that mob x gets killed 100 times. 
50 of the times, the player was on a quest, and so let's say in 25 of the cases, a quest item dropped, the other 25 nothing dropped.  
The other 50 kills, the player was not on the quest and no quest item drops of course.

That gives us a total of 25 drops in 100 kills, or a 1 / 4 overall drop rate. This would in the databases be indicated as 25%. But this is not correct as going by my example above, the actual drop rate for the quest item is 50%.

This gives us with a problem of figuring out just how much lower the drop rate stated in various sources for quest items is compared to what it should be.

**Comment by Phatcat** [comment]
@katz1 If you want to look up actual drop rate info from back then please use cached allakhazam, as this is the only real reliable source for cached db info from the actual retail game.

https://web.archive.org/web/20070225201319/http://wow.allakhazam.com/db/item.html?witem=5064 - states a somewhat lower drop rate for this item (illustrating what I was talking about in the other comment). But wait. this is almost half what both thottbott and wohead states.... That's weird.

Let's just take a look, shall we...:
http://web.archive.org/web/20110907060808/http://thottbot.com/item=5064 (from 2011)
http://web.archive.org/web/20131024004309/http://www.wowhead.com/item=5064 (from 2013)
(couldn't find anything earlier sadly)

Not to cause offense to anyone using these sites (@cala , sorry), but maybe you should consider making the switch to allakhazam. I mean how trustworthy can wowhead and thottbott be when they both state that the item was added in 1.11.1 ..... Allakhazam had the item since 2004, and still has it cached from 2005, with drop rates and everything: https://web.archive.org/web/20050224105849/http://wow.allakhazam.com/db/item.html?witem=5064
I didn't even play when that site was cached, I was 12 then. I didn't play till I turned 13. Which was way before 1.11 ...

Yeah, Allakhazam had the quest (and most likely also the item by that) added around april 2004; https://web.archive.org/web/20050103175956/http://wow.allakhazam.com/db/quest.html?wquest=867

I at least know who I want to put my faith in having the correct values, just as I did back then....

**Comment by katz1** [comment]
Thanks for shedding some light on the subject.

I tried looking up this quest because it was a **lot** slower to do than the other Barrens quest. But it turns out now that all the previous quests were full of the incorrect 80% drop rate. For example check these items: 5087, 5086, 5096, 5062

In some cases the other sources you mentioned seems to miss data or having clearly incorrect values (like thottbot saying Raptor Head drops with 2%...). Maybe it would be the wisest to scale the drop rates in these cases based on the number of items needed for the quest and the availability of the mobs dropping the items. The ~40% looks fair for me when 8 items are needed and a lot of mobs are available.

I am closing the PR, but please continue the conversation if you have any more to add.

**Comment by Phatcat** [comment]
@katz1 actually I was arguing NOT to use thottbott or Wowhead, ever, for anything, at all. Please ONLY use allakhazam for db stuff was my point (and wowwiki if possible for extra reference, or any other wiki site sporting a 'history' function so you can go back in time to mid - late 2006 / early 2007 ... Even though wiki sites usually don't sport a lot of details on db stuff)

I advice anyone wanting to research db stuff to get familiar with waybackmachine.org and old allakhazam (that last one is a bit tricky given that the old site only exists cached now.... forget finding anything in the new allakhazam, that place is a joke. Good luck)

**Comment by Phatcat** [comment]
5062: https://web.archive.org/web/20070112060108/http://wow.allakhazam.com/db/item.html?witem=5062 - seems to have more than reasonable drop rates; much higher than Witching Talons.

5086: https://web.archive.org/web/20071201081500/http://wow.allakhazam.com/db/item.html?witem=5086 (sadly from late 2007, but the only one closer to vanilla is from april 2005, which is even further away from 1.12.1 ...) - seems to have a bit lower drop rate, but nothing too unreasonable.

5087: https://web.archive.org/web/20070111200838/http://wow.allakhazam.com/db/item.html?witem=5087 - again, seems just a bit lower than Witching Talons, but nothing unreasonable.

5062: https://web.archive.org/web/20070109174435/http://wow.allakhazam.com/db/item.html?witem=5096 - high drop rates; almost as high as the raptor heads.

Have I proven my point yet? do I really have to start begging for people to not use faulty sources?

The reason allakhazam is so superior by the way, is because it was made using their own sniffing tool called wowreader. they then parsed this info and logged it into their own db system.
Allakhazam was run by actual programmers and db people. Dunno what thottbott and wowhead was, always hated those sites.

**Comment by Tobschinski** [comment]
After seeing countless mistakes on allakhazam, thottbot and wowhead, I do not trust any of them. :)

**Comment by Phatcat** [comment]
@Tobschinski Nothing is perfect, but allakhazam is a hell of a lot better than any of the others. Good luck finding all the data in your personal sniffs vs their several thousand users sniffing for them back then (including me). Also their data is publicly available. Sniffs from developers we have to trust their word they are not fabricating info. I doubt anyone would, though, so why not give allakhazam the same benefit of doubt given to fellow source developers?

**Comment by Tobschinski** [comment]
Well, we can easily check that. Let's have a look at the chance for item 1006 to drop, required to complete the quest "Princess Must Die!"

Allakhazam [59.56%](http://web.archive.org/web/20060725012530/http://wow.allakhazam.com/db/item.html?witem=1006)
Thottbot [73.6%](http://web.archive.org/web/20070328172617/http://www.thottbot.com/i1006)
Wowhead [65%](http://www.wowhead.com/item=1006/brass-collar)
Tobschinski 100%

Who are you going to trust?

**Comment by Phatcat** [comment]
> The thing that can end up being really confusing when figuring out the actual drop rate for quest items when using values from ANY source WHATSOEVER is that there is no indication of how many of these kills happened with someone on the quest.
> (...)
> This gives us with a problem of figuring out just how much lower the drop rate stated in various sources for quest items is compared to what it should be.

Are you suggesting that princess was never killed by anyone not on the quest or that their data should not be included in the db?

**Comment by Tobschinski** [comment]
No, I am not suggesting this, which is exactly the reason why allkahazam, thottbot and wowhead are pretty useless for quest items.

**Comment by Phatcat** [comment]
So you suggest to straight up just guess on quest item rates? Or are we back to the single developers sniff data worth more than a whole db full of it? Because it's easy to spot the 100% ones, it's all the others that are tricky.

**Comment by Phatcat** [comment]
Using your senses, the quest text and your general knowledge of the game would allow you to reach a conclusion of 100% without looking at any db or sniff data at all. But not all quest items are 100% , and not all quests are this obvious in the text about the drop rate. (all quests asking you to kill a named mob for a named item are 100% - are there ANY exceptions to this at all? I bet they could be counted on one hand if any) - Now go ahead and find a NOT 100% quest item and show me how YOU find the correct drop value for it then, not using any of these sites as a base for the value.

> After seeing countless mistakes on allakhazam, thottbot and wowhead, I do not trust any of them. :)
> (...)
> Allakhazam 59.56%
> (...)
> Who are you going to trust?

So classifying this as 'countless mistakes' is being dishonest. What I showed from thottbott and wowhead was actual mistakes. I may be judging them hard. they may actually be worth a little, but not the newer sites, it has to be cached data from back then at least, and it seems like most of that is lost.  What you showed however was perfectly fine data improperly analysed and mistakenly concluded to be faulty.

This issue is also only occuring with quest items, so outright not trusting any of these sites simply cause of this is weird. Could you please provide me with some valid reasons not to straight up copy-paste all their rates for anything non quest item? (I of course don't mean that literally, but you get my point; their rates are closer to the real rates than ANYTHING anyone else could provide) Because your sniff data is better? - I do not trust thottbott and wowhead because there is no indication where they got their data from. did they sniff it? fill it in themselves? copy it from allakhazam? how did they get their data? you however seem to just have a personal distaste for them because..... 'reasons'?
Is it because Allakhazam is available to everyone and sniff data is something only a few of you guys got? If it's not simply elitism then I do not get the logic of you db people...

**Comment by Muehe** [comment]
> If it's not simply elitism then I do not get the logic of you db people...

He just backed what you said, that sniff data is not reliable for quest items, because not everyone who killed "Princess" was on the quest "Princess must die!", hence reported drop chance is < 100%.

Btw. this is bound to get worse with more people sniffing, cause chance of 1000 people killing Princess while not on quest is higher than the chance for a single person. Also, even Allakhazam had a spam problem back in the day, with people reporting non-existant items or wrong drop chances deliberately.

**Comment by Tobschinski** [comment]
No, I do not blindly trust their data for any type of loot, not only quest items. Or even data in general.
- Faction: Do these databases take into account which faction has killed the creature? Because items exist that are exclusively dropped for either one or the other faction.
- Level: Do these databases take into account what level the killed creature had? Because a different creature level will result in different item level that are being dropped.
  A level 17 murloc will drop other items than a level 19 murloc, even if they share the same id.
- Amount: A lot of creatures were sniffed less than 200 times. I can only image the huge amount of items missing that have never been seen because they just did not drop.
- Obvious mistakes: Trusting allakhazam.com, Garr is supposed to drop Stranglekelp. Where does this data come from if the sniffer is so accurate? Why do Corehounds drop Fireworks?
- Grouping: A lot of items are grouped. You get one or the other (e.g. cloth). I don't see that information on any db.

Click [this](http://web.archive.org/web/20060415044733/http://wow.allakhazam.com/db/mob.html?wmob=12099) for an example.

Firesworn are level 60 creatures that do not drop any loot or money. Trusting Allkhazam, level 55 Firesworn do exist, dropping money and 4 green items players can equip.

**Comment by cyberium** [comment]
Well guys, we don't care about your feeling of "whats the best source. **We dont have direct access to old Blizzard DB** so **we dont have any trusty source for data**. Even sniff may be missreaded. But we are all ok to say sniff is the most correct data that we can have.
This point our need to try to verify as much as we can and if we dont know the real value after all research then we can suggest one, discuss about it, and clearly identify it in core/db as may not be correct one.

Everyone know that DB devs are not elitist they only try to include the best value they can in the DB.
They used to search all source they can have, including allakhazam, youtube or such. Some here seem only discovering how hard is the DB work :)

cheer

**Comment by cala** [comment]
I agree with @cyberium . In my opinion, their is no reliable source, only sources that are less unreliable than others.

When doing DB work, sometimes this is not possible to find the correct value, especially for drop rates as everyone here noticed. So, we are facing two options:
1. do nothing and keep an obviously broken value because we want only 100% accurate data
2. try to change the broken value to a better one, though inaccurate

Achieving the first case is extremely unlikely because we don't have and will more than probably never have access to Blizzard DB as @cyberium stated.
In my opinion (and this is mine, not some kind of golden law), we should aim to the second case while stating that we are aiming at it. For example, when fixing a drop rate value, I usually also link the sources I used to define that value. It gives the opportunity to someone to review, challenge and maybe fix that value.

I prefer the later approach because it allows to converge towards a more Blizzlike DB though we all know we will never 100% reach it. And if in the process we do something that is inaccurate, I'm always open to improve it, update it or even reverse it, as you know. The tricky part here is to do the distinction between what is inaccurate but acceptable and what is clearly wrong. This is finding the complex balance between a DB that is proper and very accurate and one that is playable and gives a blizzlike feeling with few clearly broken things. Tough and long job.

**Comment by Phatcat** [comment]
@Tobschinski First I'd like to thank you for taking your time out to present me with some solid reasons.
But again, some of the things you mention, you do not mention any sollution to, like;

> A lot of creatures were sniffed less than 200 times. I can only image the huge amount of items missing that have never been seen because they just did not drop.

Yet you think you can get the info from your own sniffs? - Still the data on these sites about the drops are valuable, since this info may not be available any other place. If allakhazam sniffed them less than 200 times, how many times do you think you sniffed it? and how many items do you think may be missing from your sniffs then?

> Level: Do these databases take into account what level the killed creature had? Because a different creature level will result in different item level that are being dropped.
> A level 17 murloc will drop other items than a level 19 murloc, even if they share the same id.

This basically only goes for world loot, and no, I agree that world loot is really a tough one to figure out how to do properly, but if you take a look at these kind of mobs and their drops, their drops are classified as world loot in allakhazam. Are you proposing to build a world loot system not using allakhazam and other cached db's? - I am not saying to trust them blindly, but I'm saying not to disregard them as inhenrently flawed just because a lot of their generic data is mashed together?

> Faction: Do these databases take into account which faction has killed the creature? Because items exist that are exclusively dropped for either one or the other faction.

Basically:

> Using your senses (...) and your general knowledge of the game would allow you to reach a conclusion

These items are few, and usually well documented / commented on, since they are special cases... It's all the 'generic' cases that are not well documented in comments where data in quantity is better than data in quality.

> Grouping: A lot of items are grouped. You get one or the other (e.g. cloth). I don't see that information on any db.

And neither is that info in your sniffs, so:

> Using your senses (...) and your general knowledge of the game would allow you to reach a conclusion

## 

> Obvious mistakes: Trusting allakhazam.com, Garr is supposed to drop Stranglekelp. Where does this data come from if the sniffer is so accurate? Why do Corehounds drop Fireworks?

This is however a very valid reason in my opinion, and so you've hammered home your point about everything being taken with a grain of salt, I get that now.

I'm not saying to trust them blindly, but they have statistical data that no collection of private sniffs can ever match, and it's build using sniffs, so saying not to trust them, but to trust sniffs, this is where the logic is dropped on me.

I'm not saying you guys sniffs are not good, but they are good for quality data, spawn points, patrols, stuff like that, where this is regarding data where statistical data is worth a great deal more if understood properly.

**Comment by Phatcat** [comment]
> Click [this](http://web.archive.org/web/20060415044733/http://wow.allakhazam.com/db/mob.html?wmob=12099) for an example.
> 
> Firesworn are level 60 creatures that do not drop any loot or money. Trusting Allkhazam, level 55 Firesworn do exist, dropping money and 4 green items players can equip.

Also you need to understand how to read allakhazam, there is a difference between mob value and money drop. Mob value is the median sell value (it may be the median vendor buy value actually) of the loot on a kill. Don't lose me completely here, @Tobschinski

In fact, I would rather argue that all those items on that list there proves that this mob had a small chance for an uncommon world loot drop. I would like for you to straight up disprove that, if you will.

You don't have to, I'm going to prove it using your own god damn logic;

> Amount: A lot of creatures were sniffed less than 200 times. I can only image the huge amount of items missing that have never been seen because they just did not drop.

*Edit: Wait a second.... you say the mob is not supposed to have any loot at all.. how about all those solid stones and all that deeprock salt then? You know what. I don't believe you. I think you actually don't know what you're talking about.

**Comment by evil-at-wow** [comment]
> You know what. I don't believe you. I think you actually don't know what you're talking about.

This is actually fairly easy to verify. These Firesworn are adds of Garr, so all you need to do is kill Garr a few times in Molten Core. Say over the course of several weeks - Molten Core is a raid as you know, so you can only kill him once every reset - and with several characters a week if that's possible. When you have 25 kills (or 50, or 100, or whatever number you're comfortable with), report back with the loot the Firesworn have dropped. I think you'll be surprised!

That said, I can see your point and I'd even go as far as saying we basically all agree with each other here: there is no reliable source for loot data, period. Not our own sniffs, and not any website. Please note that Tobschinski doesn't say those websites are useless. He only says he doesn't trust them blindly. Using common sense to filter out bogus data is good, and I'm sure you agree.

Our own sniffs have value because they can prove something can actually drop given (possibly unknown) conditions like quests you were on, your race/class/level/whatever. They can prove it is possible that some Molten Core boss can drop the same purple item twice. They can prove that it is possible that a mob doesn't drop anything at all (note that I'm not saying we can prove the mob will never drop anything). And they can sometimes be useful in giving a _hint_ for the actual drop rate: when you kill a given mob "only" 19 times and you get an item 12 times, that's a 63,2% rate. So perhaps the actual drop rate, given an infinite number of kills, would be 66,66....% or a 2/3 ratio? Of course, we'll never know for sure, but I'd say it's much more likely that official servers are using pretty straightforward ratios (1, 1/2, 1/4, 2/3, etc) rather than say ratios like 17160/25823 or something silly like that.

And the websites are generally speaking quite useful because, as you say, they usually contain data from many players and for far more drops than we'll ever see ourselves. With some common sense applied to interpret the results, they certainly have value, but you know that too.

> Sniffs from developers we have to trust their word they are not fabricating info.

Actually, and surprising as it may be coming from someone who has shared sniffed data on numerous occasions, I'd say no. In general we should treat them with some doubt and common sense as well for two reasons. First, I can give you data and tell you it's coming from my sniffs, but there is no way for you to guarantee that. So from your point of view I'm as reliable as you think I am, which might be more or less reliable than any other website, depending on how you feel about me. Second, while I do not fabricate a single bit of data I post, I guess you never know there's a subtle bug in one of my tools that results in me posting wrong or skewed data, without me even realizing it. 

So as Ronald Reagan used to say: trust, but verify! And I think we all agree with that.

**Comment by Phatcat** [comment]
> This is actually fairly easy to verify. These Firesworn are adds of Garr, so all you need to do is kill Garr a few times in Molten Core. Say over the course of several weeks - Molten Core is a raid as you know, so you can only kill him once every reset - and with several characters a week if that's possible. When you have 25 kills (or 50, or 100, or whatever number you're comfortable with), report back with the loot the Firesworn have dropped. I think you'll be surprised!

Where should I verify this, though? On Blizzards brand new old school servers?
Oh, you say go to live? Where everything always stays the same.

Just to show you guys I'm not a complete idiot, I do know that that mob doesn't drop anything, I did raid MC quite a few times back then.... Please don't treat me as if I've never heard of a raid before, I have over 100 /played days on my main during vanilla and 50 /played days on my main through tbc, I was however trying to prove a point about statistical data.

As I kept repeating; use your common sense (and a little bit of effort, a bit more than **some** of you guys **seem** to put forth...), you can still reach this conclusion just using allakhazam.

Look here: http://web.archive.org/web/20050414020403/http://wow.allakhazam.com/db/mob.html?wmob=12099 this is the mob from april 2005. Only 11 looted kills.

http://web.archive.org/web/20060415044733/http://wow.allakhazam.com/db/mob.html?wmob=12099
And here we have 293 looted kills on april 2006, a year later.

Fast-forward one and a half year further and http://web.archive.org/web/20071104131300/http://wow.allakhazam.com/db/mob.html?wmob=12099 294 looted kills

Could it be that these possibly had loot before the introduction of BWL? - Perhaps they had loot on a public test realm or simply as a bug blizzard introduced themselves for a short period?

**Comment by evil-at-wow** [comment]
We all know that things change constantly on live servers, just as we all know that they don't change everything all the time so many things don't change for years and can still be tested with a certain degree of trust. But it is a fact that they do change things in old content - they once changed the model of the Molten Giants and Molten Destroyers during Cataclysm for example - so point taken. You can't verify that claim any more with 100% certainty.

And please don't feel personally addressed when I give some more details than you strictly need (also note that I nowhere even suggest you're an idiot). While my post may have started as a reply to something you've said, I am posting this in a public place where most likely several, and perhaps many, people will read it one day. I don't assume or expect that everyone who might read my post has the same level of knowledge and expertise. Someone who has played the game but has never raided might not even realize that Molten Core bosses can only be killed once a week and thus could have wondered why I said it takes weeks to kill him a few times. Granted, I think those are few around here, but you never know. So I often add a few extra words (some will say I just tend to dump walls of text) to clarify things a bit and allow the 'ignorant' to search more info if needed, while those who have raided MC in the vanilla days like you, or those who know what I'm talking about, can just discard it. No harm done.

Talking about assumptions...

> and a little bit of effort, a bit more than you guys seem to put forth...

Saying things like that is not needed. For starters because you have absolutely no idea of the effort and time many of us have already put in projects like this.

Be nice to people. They tend to be nice to you as well when you do that :smile:

**Comment by Phatcat** [comment]
> Be nice to people.

I'm trying... Not quite good at it, though.

**Pull request closed without merging**
