### PR TITLE
#292, #293, #295, #298

### PR DESCRIPTION
**Pull request by Tobschinski**
[Quest - Counting out Time](https://github.com/classicdb/database/issues/292)
[Vendor - Quartermaster Hasana](https://github.com/classicdb/database/issues/293)
[Quest - Craftsman's Writ](https://github.com/classicdb/database/issues/295)
[Quest - Argent Dawn Commission | Scourgestones](https://github.com/classicdb/database/issues/298)

### CODE REVIEW

**Comment by Schmoozerd** [comment]
A small note: you should not use the "mangos." in the sql-files (the database might be named differently)

Probably easiest is to fix the commits (git rebase -i) and then force-push them to your pull-request branch ;)

**Comment by Tobschinski** [comment]
oh, I explicitly added that everywhere ...
I guess i need another week to understand your second point ...  : )

**Comment by PatSmuk** [comment]
Thanks for the request but a few things:
- Please use more descriptive commit messages. For example instead of "292_Quest_Counting_out_Time" use "Make quest "Counting Out Time" (ID: 4973) repeatable." If it fixes an issue then put "Fixes #[issue ID]." after two line breaks in the message as well.
- The format in the updates is unneeded since the updates will be deleted once they are made into a full release. This is why good commit messages are important.
- Like Schmoozerd said, never use the database name. No assumptions can be made about the what the databases are called.
- Please name updates after the table they affect (examples: https://github.com/classicdb/database/tree/b228ecb01125b9c265004d9272699597a3e57a23/updates). If it affects multiple tables please break it into pieces like 0383. Please use a placeholder ID (e.g. x001) instead of the revision code.

**Comment by cyberium** [comment]
You done it well for the first try ;)

**Comment by cala** [comment]
Thank you very much for this pull request. I'll review it as soon as I can.
I realise that the "How to contribute" part of the readme file is lacking many informations, like the guidelines posted by patman above for instance. My mistake, I'll update this soon.

In the meantime, don't bother fixing your pull request, I'll handle it. Just be sure to follow the guidelines once I'll post them. Thanks again, like cyberium said, you did well for a first try. :+1:

**Comment by Tobschinski** [comment]
Thanks all, looking forward to round 2 ...

**Pull request merged**
