### PR TITLE
[0439] Fixing xp / min & qlvl for quests in Eastern Kingdoms

### PR DESCRIPTION
**Pull request by Tobschinski**
- including zones: Tirisfal Glades, Deathknell, Undercity,
  Scarlet Monastery, Western Plaguelands, Scholomance, Eastern Plaguelands,
  Stratholme, Silverpine Forest, Shadowfang Keep, Hillsbrad Foothills,
  Alterac Mountains, Arathi Highlands, The Hinterlands, Wetlands, Loch Modan,
  Dun Morogh, Ironforge, Gnomeregan, Coldridge Valley, Badlands, Uldaman,
  Searing Gorge, Blackrock Mountain, Blackrock Deeps, Blackrock Spire,
  Molten Core, Blackwing Lair, Burning Steppes, Redridge Mountains,
  Elwynn Forest, Northshire, Stormwind, Westfall, Deadmines, Duskwood,
  Swamp of Sorrows, Blasted Lands, Stranglethorn Valley and Zul'Gurub
  
  Sources: Bradygames' WoW Master Guide and web.archive.org/thottbot.com

### CODE REVIEW

**Comment by Tobschinski** [comment]
Fixes: 
- https://github.com/classicdb/database/issues/306
- https://github.com/classicdb/database/issues/309
- https://github.com/classicdb/database/issues/311
- https://github.com/classicdb/database/issues/313
- https://github.com/classicdb/database/issues/315
- https://github.com/classicdb/database/issues/317
- https://github.com/classicdb/database/issues/319
- https://github.com/classicdb/database/issues/321
- https://github.com/classicdb/database/issues/323
- https://github.com/classicdb/database/issues/328
- https://github.com/classicdb/database/issues/329
- https://github.com/classicdb/database/issues/330
- https://github.com/classicdb/database/issues/331
- https://github.com/classicdb/database/issues/333
- https://github.com/classicdb/database/issues/334
- https://github.com/classicdb/database/issues/335
- https://github.com/classicdb/database/issues/336
- https://github.com/classicdb/database/issues/337
- https://github.com/classicdb/database/issues/338
- https://github.com/classicdb/database/issues/339
- https://github.com/classicdb/database/issues/340
- https://github.com/classicdb/database/issues/341
- https://github.com/classicdb/database/issues/342
- https://github.com/classicdb/database/issues/343
- https://github.com/classicdb/database/issues/344
- https://github.com/classicdb/database/issues/345
- https://github.com/classicdb/database/issues/346
- https://github.com/classicdb/database/issues/347
- https://github.com/classicdb/database/issues/348
- https://github.com/classicdb/database/issues/349
- https://github.com/classicdb/database/issues/350
- https://github.com/classicdb/database/issues/351
- https://github.com/classicdb/database/issues/352
- https://github.com/classicdb/database/issues/353
- https://github.com/classicdb/database/issues/354
- https://github.com/classicdb/database/issues/355
- https://github.com/classicdb/database/issues/356
- https://github.com/classicdb/database/issues/357
- https://github.com/classicdb/database/issues/358
- https://github.com/classicdb/database/issues/359
- https://github.com/classicdb/database/issues/360
- https://github.com/classicdb/database/issues/365

**Comment by Swater96** [comment]
<3 Man people leveling at 1x rates are going to hate this ;D

**Comment by Tobschinski** [comment]
They need to feel the real pain as I felt back in 2005.

I have removed ~1.700.000 exp from the game!

**Comment by PatSmuk** [comment]
Accepted! Thanks! :smiley:

**Comment by Tobschinski** [comment]
For now, Horde is way overpowered! NERF BLIZZ!

**Comment by cala** [comment]
@Tobschinski this is a true work of patience and an awesome one! Many thanks for that!

> For now, Horde is way overpowered! NERF BLIZZ!

I LOL'ed :)

I randomly checked some of the values in your pull request with other sources from 2006 and they all match. :+1: 
I did that because @Patman64 and myself are starting a huge rework of the creature data and knowing that Bradygames book is a truly reliable source will be pretty useful for that work.

**Comment by Swater96** [comment]
stats and damages, cala?

**Comment by cala** [comment]
Yes, mostly health, mana and combat stats. Immunities and resistances are not concerned.

**Comment by Tobschinski** [comment]
@cala What other sources? Do they include reputation as well? Because Bradygames and web.archive.org do not have proper information about reputation rewards.

**Pull request closed without merging**
