### PR TITLE
[] - Ruins of Ahn'Qiraj - Changes to Qiraji Swarmguard

### PR DESCRIPTION
**Pull request by Tobschinski**
- Position
- Movement (running)
- Size, Walk- & Runspeed
- Linking to Kurinnaxx

### CODE REVIEW

**Comment by Tobschinski** [comment]
Hola,

a few changes to the Qiraji Swarmguards in AQ20. The way-points are directly taken from retail, the size and movement-speed are an estimate.

One thing to add:
Using db_scripts_on_movement may not be the best solution to let them run, because the script will be executed every time on waypoint 1.
If anyone knows a better solution, please let me know.

Part (1/3) of https://github.com/classicdb/database/issues/427

**Comment by cala** [comment]
Thank you for this pull request that I will review as soon as I can. 

Regarding the run/walk toggle, I have no better solution yet. I will think of it.

**Comment by cala** [comment]
Regarding the scripts: as all the creatures have their own script doing the same thing than the other one, you can use only one script instead.
Also, as the script is currently written, the NPCs will start running and never stop doing so. I understand you were intending them to resume walking at some point and that should be random (still thinking how to do it).

**Comment by Tobschinski** [comment]
Hi, it is intended that they never walk, some creatures do always run. You could update the walking speed to match the running speed but I do not think that is the correct way. 

If you look at `SELECT `entry`, `name`, `speedwalk`, `speedrun` FROM `creature_template` WHERE (`speedwalk` > `speedrun`);` 
you will find lots of cases, where the walking speed is bigger than the running speed. I'd think these come from the assumption, that creatures are always walking.

I've even done it myself at Battleguard Sartura.

-> Another good example to see the differences are the Lava Surgers in MC, some do always run, some are walking.

**Comment by Tobschinski** [comment]
Oh, and I wasn't sure about the script-table. If the `id` is built out of the `guid` + an auto-increment, I'd rather store 6 entries. But that is up to you, of course.

**Comment by cala** [comment]
> You could update the walking speed to match the running speed but I do not think that is the correct way.

Triggering them to run is more proper than modifying their walk/run speed. In fact, I assume many of the creatures with walk speed > run speed where manually modified to make them move as fast as if they were running and I'm not sure it should have be done this way.

Thank you for your answer. :+1:

**Comment by Schmoozerd** [comment]
If there is a generic requirement for some npcs to be running by default, it might be reasonable to add some sort of flag (by guid?) there in some way.

But this requires research if they are really running or just have high walk-speed.
(also what is the difference between running and walking in the opcodes and where/if we can see how they are set by default in sniffs.)

(actually running is i think the existance/ removal of a flag in their movement package.)

**Comment by cala** [comment]
Accepted, thank you.

Regarding the walk/run speed toggle. I think this is a more generic issue that just those NPCs and it should be dealt with separately.

**Pull request closed without merging**
