### PR TITLE
creature: Kroshius (spawn location)

### PR DESCRIPTION
**Pull request by Phatcat**
Pull rrequest made on behalf of @killerwife correcting the spawn location of Kroshius.

### CODE REVIEW

**Comment by cala** [comment]
Thanks.
@killerwife : I assume the spellfocus GO must also be relocated in the same place?

**Comment by killerwife** [comment]
The GO should be in the correct position already.

**Comment by cala** [comment]
Not in Classic DB. Currently, the NPC and the GO have the exact same location. I looked into TBC-DB and other sources and saw that it is spawned elsewhere. I fixed this. Thank you for your contribution.

**Comment by killerwife** [comment]
Alright then, I didnt know that, but hey at least its all good now.

**Pull request closed without merging**
