### PR TITLE
[] - Temple of Ahn'Qiraji - Changes to Bug Trio

### PR DESCRIPTION
**Pull request by Tobschinski**
- Position
- Movement
- Stats, Scale, Runspeed & Respawn
- Linking

### CODE REVIEW

**Comment by Tobschinski** [comment]
Worst movement behavior I have ever seen. I would like to know why it would have been necessary to add 3 different patterns (on retail) ...

**Comment by wowpsp** [comment]
Thanks for your pull request, I was preparing to submit a similar pull request.. 
But the database is too large, cala couldn't make everything looks the same as Blizzard, we have to thank cala for his great contribution, we work together and make classicdb better

**Comment by Tobschinski** [comment]
Oh, this wasn't addressed to cala. More to the one that have been adding movement on retail.

**Comment by wowpsp** [comment]
:  ) Thank you

**Comment by cala** [comment]
Thank you very much for all those pull requests. I will review it very soon.

Can you please give us a bit more info regarding: the waypoints and and HP values (I guess you observed them on retail, but just to be sure)?

Still regarding health values, as you may already know, we are currently in the middle of a major transition regarding creature stats. Thus, I might delay for a while the part of your PR related to health and such. Just to let you know.

**Comment by Tobschinski** [comment]
Waypoints and the positioning are directly taken from retail. I doubt there have been changes to them.

And yep, I know health values will be obsolete soon but ...

... some mobs have a different minimum level, so I had to change that. In order to get rid of load-up warnings, I had to make changes to health values too.

That's why I added them to my check list.

**Comment by cala** [comment]
> And yep, I know health values will be obsolete soon but ...

They won't be obsolete, but we will have to check almost every creature in the database to adjusts stats, looking for errors, starting with health and mana values.
So my question was about the change to `minhealth`, `maxhealth` and their mana equivalent that you make to `creature_template`. If those values come directly from retail (and I understand they do), then they are very valuable to us. :+1:

**Comment by Swater96** [comment]
Waypoints are the same in retail, only in cata they added a system that made directional changes 100x smoother.

**Comment by Tobschinski** [comment]
Oh by the way, should I change Vem's movement to creature_movement_template? Or would that not matter at all (for you)?

**Comment by cala** [comment]
Yes, please. Vem being a unique creature, its movement belongs to `creature_movement_template`.

**Comment by evil-at-wow** [comment]
> I would like to know why it would have been necessary to add 3 different patterns (on retail) ...

Can you elaborate a bit, please? You mean each of them has its own movement, different from the others?

**Comment by Tobschinski** [comment]
That was more of a rhetorical question.

And yes, Vem has three different ways to move from the right to the left side and back in its lair. The small area will be crowded with a huge amount of wps. And due to that, adding wps was a pain, that's why I was complaining!

**Comment by cala** [comment]
Accepted, thank you.

**Pull request closed without merging**
