### PR TITLE
Various Fixes to Winter Veil

### PR DESCRIPTION
**Pull request by Zingzah**
This is a list of fixes to the winter veil.  I don't know how to remove my update PR's from my repo.  Any help would be appreciated but pls ignore those.  Just the bottom PR with the fixes is intended.

### CODE REVIEW

**Comment by Zingzah** [comment]
Thank you Rush.  I forgot to add a more detailed notes on my changes so here they are.

This is a collection of fixes to the current Winter Veil event.  There were a few issues I wasn't able to resolve and will need some help with especially since I think they involve core work with spells and whatnot.  I have taken data from trinitycore for a few of the fixes to save time.  A big thank to trinity for all the great work.  These were areas where there wasn't a change between the vanilla and wotlk data.  I will mention these instances as they are listed.

Details of the fixes are as follows:
1.  The two winter hats (red + green) corresponding boss loot tables and Christmas hats adorning models for each boss have been added (only during the winter veil event) according to:
   http://web.archive.org/web/20070202022332/http://www.wowwiki.com/Red_Winter_Hat
   http://web.archive.org/web/20070307231602/http://www.wowwiki.com/Green_Winter_Hat
   I have made each boss drop 1 hat per defeated boos although I haven't investigated how to add these two items as world drops (possible yet?).
2.  Enclosures for Metzen in both  Searing Gorge and Tanaris have been added as these were missing.  Position data were used from trinity in these instances.
3. Goli Krumn's position has changed according to the few visual sources I could find - 
   http://www.wowhead.com/npc=1365/goli-krumn and
   https://www.youtube.com/watch?v=r1itpKySuks
   The video is from 2011 but there is a screenshot from 2007, both corroborating the correct position for this npc.
4. The Holly Preserver position in Ironforge was in a different place in vanilla as indicated by one of the photos on this page:

https://www.flickr.com/photos/afkgamer/sets/72157594429282664/
(please try to ignore the gnomes on top of the smokywood pastures cart)

and a corroborating screenshot shows the preserver piping showing from behind the cart in this screenshot (just to the right of the bottom most hanging axe decoration)

https://chowonline.wordpress.com/2006/12/23/review-world-of-warcraft-feast-of-winter-veil-seasonal/ 

-2nd picture from the left (ss8.jpg)
The fixes contain a position change for this object accordingly.
1. There were a quite a few problems associated with the Hero of the Day quests in both the alliance and horde versions.  Requirements of completion of the Saving Metzen quest, a cooking skill of 300 and race have been added as well as text field adjustments for the quests. Repeatability has been removed as well.

http://web.archive.org/web/20071218141527/http://thottbot.com/q8763
1. There are three instances during Winter Veil when follow up messages and rewards were received after completing Treats for Greatfather (Great-Father) Winter, Metzen and Stolen Treats quests.  These were added according to comments for the items listed below:

http://www.wowhead.com/item=17726/smokywood-pastures-special-gift
http://www.wowhead.com/item=21216/smokywood-pastures-extra-special-gift
http://www.wowhead.com/item=17685/smokywood-pastures-sampler
1.  The Winter Veil presents were added thanks to trinity core's implementation.  It has been added as a separate event(52) with present placement data coming from trinitycore.  The presents bread crumb quest was moved to this event.  The New Years bread crumb quest was also moved from the Winter Veil event to New Years.  OfferRewardText was added to all gift and present quests which was originally missing. A class distinction(mana and non-mana users) was added to the two Gently Shaken Gift quests to correctly award roasts or eggnog.
2. The Abominable Greench has been modified to have multiple (4) spawn points and a respawn timer of 10 minutes according to comments listed in:

http://web.archive.org/web/20071218085425/http://thottbot.com/c13602
1. Finally, the mechanical greench companion was fulled sized when summoned and should be a fraction of this, and so has had its scale adjusted accordingly.

In additon to these fixes there were issues that weren't able to be resolved and I would appreciate any suggestions where I should start to complete the following fixes:
1. I wasn't able to change Darkmaster Gandling's model for the Winter Veil event due to this being a summoned npc.  I'm not sure whether this needs to be handled within the script for this boss or somewhere in the DB.
2.  The companions obtained during this event don't currently summon when used. I have already tried setting the "activated with right-click" option in the item_template table with no change.  These include:
   
   -Jingling Bell
   -Snowman Kit
   -Red Helper Box
   -Green Helper Box

I suspect the spells for these items are not currently implemented/functioning core-side. I would appeciate any suggestions and starting points to investigate where these items are failing.

Overall the Winter Veil event is working very well and with these fixes is closer to being fully functional.

**Comment by cala** [comment]
Very nice, thank you ! I'll review it soon(tm).

**Comment by Zingzah** [comment]
I've managed to fix the winter veil companion items listed above and will be posting in a follow up shortly.

**Comment by cala** [comment]
Poke to myself about testing this.

**Comment by cala** [comment]
Accepted, thank you: https://github.com/classicdb/database/commit/1047cd4d34fb70ebcbb4b67fb7db63b2251fbb7e :+1:

**Pull request closed without merging**
