### PR TITLE
[] - Temple of Ahn'Qiraji - Changes to Vekniss Drone

### PR DESCRIPTION
**Pull request by Tobschinski**
- positioning
- amount
- stats
- respawn
- linking
- movement

### CODE REVIEW

**Comment by Tobschinski** [comment]
I hope you will once more not mind that I did not use / update the given creatures. As you can imagine, this would have been much more work.

**Comment by cala** [comment]
As mentioned in https://github.com/classicdb/database/issues/405 I'm not sure using `creature_linking` over `creature_linking_template` is the way to go. It works, sure, but you use more than a hundred similar entries that could all be gathered into one, only to not include a few ones (that we maybe should handle via SD2).
I need to think a bit about it.

**Comment by Tobschinski** [comment]
Yeah, that's why I was thinking of a flag that does nothing but overwriting.

Another example for this will be the Qiraji Scarabs and Scorpions. Only the ones inside the Twin Emperor's lair will not (re)spawn if Twins are dead.

**Comment by Schmoozerd** [comment]
well, just use the linking with some radius > 0 and you will get this behaviour well enough i think.

**Comment by Tobschinski** [comment]
There are some bugs outside the lair that have a shorter distance to the boss  than the ones inside.

And this will not work for the tunnel.

Maybe we could extend these thoughts to something like that, although it would require a massive rework of like ... everything :) 

Both creature-types, Drones and Scarabs are linked within small groups somehow. I can see that, because they will respawn on the same time, although they have been killed one after another.

What would you think if there would be a table to group creatures and link the group itself (not the creature-id nor guid) to the boss. 
That would definitely lower the amounts of stored entries and fix the current problem, that there is no way to link moving formations (as they are linked to themselves) to bosses.

**Comment by Schmoozerd** [comment]
sounds very complicated...
Sounds also rather unique and special, hence a non-db solution might be in order.

About the range issue:
Are you stating that in case of bugs partly linked to the twins, for both of the twins there always exists a bug that should not be linked that is nearer than another bug that should be linked?

What do you mean there is no way to link moving formations to bosses? Of course you can link them, why shouldn't you?
Or do you mean like linking the npcs to each other AND to the boss?

A main issue for me is to actually understand what are the needs. The more clearly you state them, and if you stated why which currently supported solution will fail, the easier it is for me to consider expansions of the subsystem.
Also assume i never had entered AQ40 :)

**Comment by Tobschinski** [comment]
Hm, not really unique. Afair every group inside every dungeon will respawn as a full group, you will probably never see creatures spawning independently. (of course they'll refill if not completely wiped out) At least I have never seen that.

Yes, as the entry for slaves is unique, you have to decide whether to link to the left or the right twin. Due to that, bugs outside the lair may be closer as one of them inside.

And yes, the second part. As you have to link following creatures to the formation master, there is no way to link them to a boss additionally. But, this would be needed very often.

Previous tries to just link the formation master to the boss have had some unwanted side-effects.

**Comment by cala** [comment]
To summarize the current topic for @Schmoozerd :

In AQ40, there is a rectangular tunnel filled with lots of mobs of the same entry. About 95% of them are linked to a boss located _outside_ this rectangle: when boss is killed, NPCs stop to respawn. This would be easy to do with creature_linking_template but the remaining 5% (randomly spread amongst the other ones) must not be linked. So, we can not use the range field to select which NPCs are linked and which ones are not.
Using creature_linking in order to only link the required ones, is working. But I wonder if it could be done more "properly".

What @Tobschinski is also saying is that there are groups of patrolling mobs, linked together (follow and respawn on evade), but those packs should also stop respawning once one boss is dead. This leads to some kind of hierarchy where most of the mobs follow a first master with waypoints movement. This same master being linked to the boss.
But with this flag combination, it seems to be possible to find a case where some mobs are not respawning when they should (or vice versa). I did not check all the logic in this to precisely spot which cases.

**Comment by Schmoozerd** [comment]
hmm, what about:
followers -> FollowAndSpawn based on Leader
Leader -> Spawn based on Boss?

or is this a case where the leader of the formation is not a unique entry?

Anyhow - expanding creature linking to link slaves:master as n:m might be possible along the lines of http://paste2.org/ptKezhW2
Note this is just some rough code thoughts, and also gets much more inconvenient than the unique linking information.
BUT it should be usable along these lines, and just yet another for loop for iterating and checking ;)
basicly one will need to replace every use of the old CreatureLinkingInfo const\* GetLinkedTriggerInformation
with the additional for loop like in paste2 lines 40-48

Though i am really not sure this is actually worth horriable problems with endless loops and similar problems that might arise with the more complexity and bad db data...

**Comment by Tobschinski** [comment]
> hmm, what about:
> followers -> FollowAndSpawn based on Leader
> Leader -> Spawn based on Boss?

In https://github.com/Tobschinski/database/blob/dbe845daf8164d928e7dd20c03e1fe8bfc51bd0f/updates/_creature_linking_2.sql, we've tried doing things like that.

The formation_slaves will somehow respawn, even with the formation_master and the boss being dead.

**Comment by Schmoozerd** [comment]
hmm, i would have expected this to work. will require somebody to do some proper debugging as test for this.

**Comment by Tobschinski** [comment]
As an addition, the exact time when formation_slaves are respawning is, when the formation_master is about to spawn (remaining 0 secs)  but will not due to its boss_linking. They won't respawn earlier.

So I would think the respawn on respawn flag of the formation_slave triggers if the formation_master is about to respawn but is not really respawning due to its linking.

**Comment by Schmoozerd** [comment]
yes, i just noticed a glitch with the "CanSpawn" check :)

The code looks like.

```
    if (pInfo->searchRange == 0)                            // Map wide case
    {
        if (!pInfo->masterDBGuid)
            return false;                                   // This should never happen

        if (pInfo->linkingFlag & FLAG_CANT_SPAWN_IF_BOSS_DEAD)
            return pCreature->GetMap()->GetPersistentState()->GetCreatureRespawnTime(pInfo->masterDBGuid) == 0;
        else if (pInfo->linkingFlag & FLAG_CANT_SPAWN_IF_BOSS_ALIVE)
            return pCreature->GetMap()->GetPersistentState()->GetCreatureRespawnTime(pInfo->masterDBGuid) > 0;
        else
            return true;
    }
```

So - with the middle-man being ready to respawn, but not respawning as of the bosses death, his saved respawn time will still be removed and set to 0, and hence his slaves, who only check his respawn-time, will be able to respawn even if they should not.

This is not trivial to fix, probably will require something a bit nasty like saving 1 as (64bit) respawn time for mobs whose spawning must be prevented in the database.

Edit: Hmm, adding some pseudo-timestamp (like 1) as dummy has some ugly impacts on many different places within the code :(
Likely something in the directions of http://paste2.org/PIpnebJN
But this needs to be done carefully, as there could be new glitches with this handling :(

Edit2:
There is an alternative to this patch by calling a (helper) function CanSpawn(Helper) recursively in addition until the end of chain (with a proper respawn time like a boss) is reached.

**Comment by cala** [comment]
After reviewing this PR, I think we can proceed with everything related to DB. There are still some related adjustments to make but we will need some updates outside the DB.

Accepted, thank you.

**Pull request closed without merging**
