### PR TITLE
[0447] Correcting drops of items 18969 and 18972

### PR DESCRIPTION
**Pull request by Sinoxan**
- Correcting drop rates of items to 2.5% and adding to unique group.
- Removing items from Lurking Feral Scar ID:7848
  Listed on this mob most likely due to bug with loot tracking software
- Added in correct PreReq quests for the items to drop
  Quest 2821 for Item 18969
  Quest 2822 for Item 18972
  Sources: Wowpedia, Allakhazam (WayBackMachine), Magelo

### CODE REVIEW

**Comment by PatSmuk** [comment]
Few issues:
- Conditions 3 and 4 are generic Alliance/Horde conditions that are used all over the place and should never be updated.
- I can't confirm that these items should only drop after completing 2821/2822. [There's a note here for the Horde quest](http://wowpedia.org/Quest:Perfect_Yeti_Hide) but the restriction doesn't seem to make sense since they aren't related and there's no restrictions on the quest itself.
- As far as I can tell the only restrictions on the drops should be Alliance/Horde.

**Comment by Sinoxan** [comment]
Oops, I didn't realise that 3 & 4 were used in multiple places.
It makes sense, you bring him 10 hides, then you unlock the repeatable quest to bring him even more hides.  They are sort of related as the quest mentions "more so than even the ones you've seen from the yeti in Rage Scar."  I guess referencing the quest you just did.
There's some contradicting data, some people only had the quest in there log and it dropped.

**Comment by PatSmuk** [comment]
I suppose it makes sense for it to be linked. Since you have to collect 10 hides in Feral Scar then collect 10 in Rage Scar, you most likely have completed the Feral Scar part anyway by the time you reach Rage Scar.

**Comment by cala** [comment]
I quickly look at this and this sounds interesting.
However, as @Patman64 noticed: never update an existing condition entry as you can never know what other gossip/template/script is using it. And those two ones are used by dozen of things.
As it is, this pull request need a bit of rework before being accepted in order to avoid breaking many things. :)

**Comment by cala** [comment]
I wanted to review more in depth this PR, but I see that files and commits are now gone. Do we close the pull request or will you push something else later instead?

**Comment by Sinoxan** [comment]
Sorry, I put this on my main branch accidentally, so it got lost once I pulled the updates from upstream.

**Comment by Sinoxan** [comment]
I updated it for new conditions, instead of changing 3 & 4.  I'm not sure how to update a pull request with a new pull so I just put it in the comment.

```
--Correcting drops of Pristine Yeti Hide (Alliance) and Perfect Yeti Hide (Horde)
--Corrected drop rate to 2.5% and into unique group.
--Removing from Lurking Feral Scar ID:7848
--Listed as dropping at very low rates on some sites, most likely due to bug where loot
--is counted to new targeted mob if you switch targets before loot window appears.
--Added in PreReq quests.
--The Mark of Quality ID:2821  ALLIANCE
--The Mark of Quality ID:2822  HORDE

--Remove old drops
DELETE FROM `creature_loot_template` WHERE `item` IN (18969, 18972);

--Add in updated drops
--ALLIANCE
INSERT INTO `creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `groupid`, `mincountOrRef`, `maxcount`, `condition_id`) VALUES (5296, 18969, 2.5, 2, 1, 1, 3);
INSERT INTO `creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `groupid`, `mincountOrRef`, `maxcount`, `condition_id`) VALUES (5297, 18969, 2.5, 2, 1, 1, 3);
INSERT INTO `creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `groupid`, `mincountOrRef`, `maxcount`, `condition_id`) VALUES (5299, 18969, 2.5, 2, 1, 1, 3);
--HORDE
INSERT INTO `creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `groupid`, `mincountOrRef`, `maxcount`, `condition_id`) VALUES (5296, 18972, 2.5, 2, 1, 1, 4);
INSERT INTO `creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `groupid`, `mincountOrRef`, `maxcount`, `condition_id`) VALUES (5297, 18972, 2.5, 2, 1, 1, 4);
INSERT INTO `creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `groupid`, `mincountOrRef`, `maxcount`, `condition_id`) VALUES (5299, 18972, 2.5, 2, 1, 1, 4);

--Set conditions to quest, instead of horde/alliance.
--HORDE
INSERT INTO `conditions` (`condition_entry`, `type`, `value1`, `value2`) VALUE (1367, 8, 2821, 0);
--ALLIANCE
INSERT INTO `conditions` (`condition_entry`, `type`, `value1`, `value2`) VALUE (1368, 8, 2822, 0);
```

**Comment by cala** [comment]
Thank you for this update and all the research that was beyond. Just a question: why put the perfect/pristine hides into a group?

**Comment by Sinoxan** [comment]
So that they can drop as well as normal loot, I spoke to @Patman64 about this and I believe that's how it works.  I always thought that quest items should be in their own group because they always dropped alongside normal loot rather than instead of.

**Pull request merged**
