### PR TITLE
[0453] Corrections to Prophet Skeram's area

### PR DESCRIPTION
**Pull request by Tobschinski**
- removed Small Obsidian Chunks
- added a third Obsidian Eradicator for later usage
- moved the three dragon NPCs
- corrected the scale of Andorgos
- added requirements for the quests dragon NPCs are giving

### CODE REVIEW

**Comment by Tobschinski** [comment]
Handles everything mentioned in https://github.com/classicdb/database/issues/144 but waypoints.

**Comment by Tobschinski** [comment]
old

retail

Patch and retail!

By the way, did you notice, that NPCs do not have their weapons attached if they are out of combat? Is that an issue? I noticed this as well when I was doing something with Captain Greenskin in Deadmines. When I put him into combat he took his pole and punched my face in.

**Comment by cala** [comment]
Thank you for this pull request! Nice job :+1: 
As I'm leaving for one week of holidays tomorrow evening, I'm not sure to have the time to reviewed it before my return.

Regarding the removal of obsidian chunks: I agree they should be removed but not until we found a way to add them properly into the game (I mean when NPCs die). This should be feasible via ACID or `dbscripts_on_creature_death` I think.

Regarding the missing weapons, there are two answers:
- if the NPC wields its weapon in combat, then its `creature_addon` is missing or wrong
- if the NPC never wields its weapon, even in combat, then it is missing its `equipment_id`

For those NPCs, this seems to be the later.

**Comment by cala** [comment]
Note, because ACID or DBScripts can not spawn wild gameobjects, there is probably a spell for this NPC to spawn the minerals.

**Comment by cala** [comment]
Spells 27627, 27628 & 27629 will spawn the small obsidian chunks.
Spells 27630 & 27631 will spawn the large obsidian chunks.
I don't remember the NPCs dropping those 100% of the time, so I guess it would be done via ACID because DBscripts do not handle random events.

**Comment by Tobschinski** [comment]
Doing a retail run just by now, they do, 1 per kill. If it has been untouched, of course ... but why would 
they ...

The Anubisath Sentinel-Fight with every single ability is scripted with SD2. Would it be better to add it there, for this case only?

**Comment by Swater96** [comment]
I can confirm a spell spawns the chunks, and also that the chunks drop every kill. (Done hundreds of aq40 runs in retail)

**Comment by cala** [comment]
Ok, so we can use dbscripts_on_creature_death to cast the spells for now. Maybe we will move it to ACID later, but for now let's do it that way.

**Comment by Tobschinski** [comment]
I need to take care of some spells anyway, some aren't working right now. Will put it there ...
Also, Anubisath Warder & Defender need to get the Drop-Large-Chunk-Spell ...

By the way, do you prefer one big update for AQ or several smaller ones?

**Comment by Swater96** [comment]
@Tobschinski I say one big update. Just add comments to each section of the code so everything is detailed. Like how I did in my current pull request.

**Comment by cala** [comment]
The size of the update is not a real matter. What matters is to keep the various topics separated for better traceability of what was changed and avoid losing track of a small unrelated change in the middle of a big one. 

In this case, everything about Prophet Skeram's area can go in the same update, as big as it may be. Fixes related to the other various AQ40 issues should go in their own separated updates. :)

**Comment by cala** [comment]
Accepted. Thank you.

**Pull request merged**
