### PR TITLE
fix creature rank (Rare)

### PR DESCRIPTION
**Pull request by kokeszko**
changes to creatures rank (Rare)

### CODE REVIEW

**Comment by Tobschinski** [comment]
Great list,

but I want to remind you of one thing.

Many quests and NPC were tagged as elite before TBC. This includes some rares as well. (e.g. Marisa du'Paige, ...)

Since this got changed during TBC, wowhead.com and even old.wowhead.com may be imprecise.

**Comment by cala** [comment]
Thank you for this great list.
However, it seems you did not confront it to current state of the database as it fixes some creatures that already were fixed. As an example:

``` SQL
SELECT rank FROM creature_template WHERE entry IN (14222, 2453, 2452,2609,3773,3792,2850);
```

already returns `rank = 4` for every entry in the query and those are nonetheless also fixed by your pull request.

I also agree with @Tobschinski regarding the fact that you mark some NPCs as rare AND NOT elite while they were rare AND elite back in Classic (and already flagged as such in the current DB).

I appreciate the effort you put in your pull request, especially the formatting, I know this is a long and tedious work. But I suggest you compare it to the current database state (where many NPCs were fixed in the past months) and that you limit your pull request to the entries that have a mismatch. If for those you could also put the link to the source that helped you determine what is the correct value, it would be perfect. A good example of what I have in mind is this commit, with both recent and old sources:
https://github.com/classicdb/database/commit/bbba40d5ab5a01559122e5bbb7b2882008c86d74
Thanks! :+1:

**Comment by kokeszko** [comment]
thx for checking this list. i'll try to correct it.
@Tobschinski, could you point more creatures which should be marked as rare elites (and are on my list, marked as elites)? i've been checking this list for a quite long time and i wasn't 100% sure for a few (and i missed comment about Marisa on WowHead about her as a rare elite before 2.3 patch).

@cala, true, i haven't been checking each creature in db if it's marked with proper flag. 
it won't be a problem, if you want an info about source of information for this pull, but it will take some time.

do you want me to close this pull, fix it and then pull request again?

**Comment by Tobschinski** [comment]
Sure, I can check your list, but I will need some time ...

**Comment by Tobschinski** [comment]
I did not check DB for current ranks!
Still, great list.

**Comment by kokeszko** [comment]
@Tobschinski, thx for a huge help. currently checking again the list and i'll try to fix it maybe till tomorrow.

**Comment by cala** [comment]
> @cala, true, i haven't been checking each creature in db if it's marked with proper flag. 
> it won't be a problem, if you want an info about source of information for this pull, but it will take some time.
> do you want me to close this pull, fix it and then pull request again?

I think checking the current DB values could save you a good deal of creatures to verify, especially in low level zones. If after the comparison, that are still a lot of changes, you can pass on providing the source. But it would be nice to have them next time.

Regarding this pull request, do what is easier to you: if you prefer to close this pull request and open a new one with an updated list, do so. But you can also choose to add commits to the current pull request in order to fix lines with wrong values or remove those already fixed. Do as you will. :)

**Comment by kokeszko** [comment]
i've already started to fixing this pull, so i won't close it. i'm providing source of information for each record and i'll filter those records which are already properly set.

**Comment by cala** [comment]
Sounds good. Thanks for your work. :+1:

**Comment by Tobschinski** [comment]
Oops, I have forgotten to add mine.

[Source](http://web.archive.org/web/20061210223559/http://wow.allakhazam.com/dyn/mobs/rare.html) - should include every rare in-game but elite ones. 
Varities have been double-checked with my beloved Bradygames' sources ...

@kokeszko Always a pleasure. Since I am recovering from an anterior cruciate ligament rupture, I couldn't be elsewhere. :)

By the way @Cala - to make rares more 'blizzlike' (I hate that word), have you ever thought of adding a min and max-spawntime field to DB instead of a fixed one?

**Comment by kokeszko** [comment]
final update is in pull request.
source of information was added.
records already marked as Rare in db, are gone now from update.

**Comment by cala** [comment]
@kokeszko Thanks for this update! We'll review it quickly (this WE or monday the later).

**Comment by PatSmuk** [comment]
Some of these WoWWiki lists are rare-elite. I might have to confirm it with my logs.

**Comment by cala** [comment]
Scarlet Smith and Scarlet Judge are rare elite at least. :)

**Comment by kokeszko** [comment]
true, wowwiki says sometimes rare elite, sometimes rare. but more valuable data (at least for me) are on http://web.archive.org/web/20061230071942/http://wow.allakhazam.com/dyn/mobs/rare.html

anyway, please check the list and i'll replace wrong records

**Comment by Tobschinski** [comment]
Scarlet Smith has 8883 Health, Scarlet Judge 7326. Should be elite, if you'd ask me.

My bad, I did not notice this allakhazam-list has additional information that are incorrect. I have just gone through your list and double-checked listed creatures ...

By the way, Achellios is still missing, what happened to him? Level 31, 1307 HP!

**Comment by kokeszko** [comment]
about those scarlet creatures. on wowhead there is plenty of information about them, and most points that they were rare guys (even with such amount of HP). on archive is shown only rank (http://web.archive.org/web/20070422004004/http://www.wowhead.com/?npc=1837 and http://web.archive.org/web/20070422004004/http://www.wowhead.com/?npc=1885),  unfortunately, there aren't any comments on allakhazam.
i'm not removing them now. please provide any othr information about those two creatures.
Achellios was chasing some ugly Ally, and will be back soon ;)

**Comment by cala** [comment]
The two Scarlet NPCs are related to Hearthglen in Western Plaguelands. In Classic this area was full of elite creatures, so I still consider them as elite and this is also OK with their HP.

Accepted, thank you.

**Pull request merged**
