### PR TITLE
Stratholme - Changes to Eye of Naxxramas

### PR DESCRIPTION
**Pull request by Tobschinski**
- added 3 spawns
- added movement
- updated walking speed

### CODE REVIEW

**Comment by Tobschinski** [comment]
Okay, some points worth to mention.
1. Fixes https://github.com/classicdb/database/issues/191
2. There is more work to be done - they do not engage players while being invisible and if they do (after removing the spell from db) they will never summon gargoyles.
3. The respawn time is an assumption. I've watched quite a few videos. In one, 23 minutes after the first kill of a spawn in ud-stratholme, players do engage another one. Regarding the fact, that there is a huge way to patrol and only one spawn, it might be 20 minutes.
   EDIT: Other source shows 18 minutes, so I use 15 minutes instead.
   
   They should respawn very fast, I remember them re-engaging players that were corpse-running

**Comment by cala** [comment]
15 minutes sounds good to me. At least, at the time I was running Stratholme with the right gear. By the end of Classic, my guild was overgeared and we usually burned through it so I can not say it is still was 15 min in 1.10 - 1.12 or if the respawn time was increased.

Regarding the remove invisibility and bats summon, this is handled by ACID. If the script is missing or incomplete, I'll look after it.

**Comment by Tobschinski** [comment]
They also should just cast their spell and then despawn, not melee players or walk close to it. That 'll be a missing flag, right?

**Comment by Tobschinski** [comment]
And if there is just one Eye to the undead side, we definitely need all tiles updated, even if there is no nearby player. At least in dungeons.

**Comment by cala** [comment]
> They also should just cast their spell and then despawn, not melee players or walk close to it. That 'll be a missing flag, right?

In this case, I think EventAI (ACID) is a better option. Adding a passive flag to those NPCs would make them unable to aggro and as such unable to cast.

After review, I will push this PR as it is and the AI part will be dealt with separatedly.

**Comment by cala** [comment]
Accepted, thank you.

**Pull request closed without merging**
