### PR TITLE
[] - Temple of Ahn'Qiraji - Changes to Anubisath Sentinel

### PR DESCRIPTION
**Pull request by Tobschinski**
- Position
- Reputation
- Stats, Level & Respawn
- Linking

### CODE REVIEW

**Comment by cala** [comment]
Regarding the linking, I'm not sure this should be done that way. I understand you want to prevent trash mobs to respawn once boss is killed, but I'm afraid the method you are using could led to unexpected behaviour because the slaves are flagged to respawn under several conditions and I'm not sure which one will be processed first.
I think it would be proper to use `creature_linking_template` for blocking respawn on master death (master being Skeram, slaves being the sentinel) and to use `creature_linking` for behaviour related only to the two trash groups (linking and respawning on evade).

**Comment by Tobschinski** [comment]
The entry in creature_linking_template will be overwritten if a creature has an entry in creature_linking. I noticed that at the core hound packs in MC.

The Sentinels would respawn even if Prophet Skeram is dead.

I will take a closer look if there are any occuring sideeffects.

**Comment by Tobschinski** [comment]
There are side effects, ~~the first one does not work as intended, some creatures will respawn.
I assume this is related to the creature guids, as the first pack's master has the lowest, the second pack's master the highest guid in their group.~~ Nope, I was just lucky there.

The second effect is related to a boss respawn, which will never happen due to the 7days respawn.

I agree, I need to find a better way ...

**Comment by cala** [comment]
Creature linking in instance is tricky. I wonder sometimes if linking shouldn't be handle via scripts in instance due to some complex cross links (like core hounds packs in MC). I'll think about it also.
And you have a point about `creature_linking` versus `creature_linking_template`. In some cases you can use both, but this does not seem to be the case here.

**Comment by Tobschinski** [comment]
Oh, we are lucky cala, the linking within the group has already been done by [SD2](https://github.com/scriptdev2/scriptdev2-classic/blob/master/scripts/kalimdor/temple_of_ahnqiraj/mob_anubisath_sentinel.cpp)!

EDIT: Yep, exactly what was on your mind has been done here.

**Comment by cala** [comment]
**cala**

> I wonder sometimes if linking shouldn't be handle via scripts in instance due to some complex cross links

**Tobschinski**

> Oh, we are lucky cala. the linking inside is done by SD2!

OK. In two days, on Classic DB alone, I managed to write three times wrong messages about things I should have known/checked before writing.
Time to have some rest and to straighten myself...

**Comment by Tobschinski** [comment]
Everything is fine, you've beaten me by one minute :)

**Comment by Schmoozerd** [comment]
We of course thought of implementing most linking issues in general over SD2 -- but this would just been huge overhead and not required.

Very special NPCs are absolutely no issue to do over SD2 (like the core-hound packs maybe), but in general one should try the following order:
1) Use creature_linking_template
1b) Use creature_linking_template with range > 0 to get some local-pack behaviour
2) If above not possible use creature_linking (remark: guids are evil!)
3) If above not possible, think if creature_linking_template can be expanded to more flexibility
4) If above not possible, consider a hardcoded solution with SD2
5) If above not possible, analyze the problem more detailed :)

**Comment by cala** [comment]
> We of course thought of implementing most linking issues in general over SD2 -- but this would just been huge overhead and not required.

And of course, I perfectly know that. Hence my "Time to have some rest and to straighten myself..." :)

However, I _think_ `creature_linking_template` is not always working like one might expect. A good example is Tendris Warpwood in DM West. When engaging him, all Ironbark protectors should attack, forcing players to kill them first. When using `creature_linking_template` with no radius, only one protector comes. Always the same, not the closest one. When using `creature_linking` with all the evil GUIDs, all protectors come.

This needs further testing and code peering when I can spare the time, but I would have expect `creature_linking_template` to work on all the nearby creatures of the same entry, not only one, at least for `FLAG_AGGRO_ON_AGGRO`.

**Comment by Tobschinski** [comment]
Oh, similar behavior as the [Anubisath Denfender](https://github.com/classicdb/database/pull/393) and the Twin Emperors, I'll check what happens to them.

**Comment by Tobschinski** [comment]
They do not engage, and I would think this is related to unloaded tiles. If I add a Defender nearby (or more), he (or they) engage (s) when I attack the Twins.

May this be the case for your situation as well, cala?

EDIT: But that would not explain why they attack due to `creature_linking`.

EDIT#2: I am sure it is, all nearby spawned Protectors engange due to a set linking in `creature_linking_template`. If I position myself that one is out of my visual range, he will not engage.

**Comment by Schmoozerd** [comment]
there might be something as simple as the npc directly evading due to being out-of-range to the player?
Or not finding a path or something related?

**Comment by Tobschinski** [comment]
As I am always falling through the world @ Warpwood, I'll give you another example :) ...

**Comment by Tobschinski** [comment]
As you can see, I am next to one of the twins. I do not see the other Twin. (Pic 1) When I am attacking the one next to me, the other will not engage combat. (I am fighting the Twin for 14 seconds now) (Pic 2)

twins1

twins2

If I move forward to get both of them in 'sight'-range, both will engage.
As it seems, there are no actions possble within the 'fog of war'

**Comment by Schmoozerd** [comment]
https://github.com/scriptdev2/scriptdev2/commit/30f07e5c1b2b06d961b76dfb32b5837eacfb3fb5#commitcomment-1519215

this must work. if this doesn't work somebody needs to debug the cases where it does not work to understand why it has issues.
(probably something along the lines of above suggested issues)

**Comment by cala** [comment]
Well, I'm currently testing Warpood and Vectus who have the same behaviour and `creature_linking_template` is working as intended. So, WDB files, I'm pointing my finger at you. Or maybe the visibility config values in mangosd.conf that were recently increased on my server.

Anyway, this should work, including the Twins Emperor that I tested 30 minutes ago.

**Comment by Tobschinski** [comment]
May it be the case, that creatures cannot target you if you are too far away? If I move away from a targeted creature, I will lose it somewhen. That happens to creatures as well, I think.

If I increase the visibility config, like cala did, even the linked Anubisath Sentinal will add to the Twins Fight, but only if I am able to target them beforehand. If not they probably cannot target you back, and will not add.

But that would not explain why the movement of pats stop when moving out of sight.

**Comment by evil-at-wow** [comment]
I don't remember the details by heart, but I believe the core only updates cells around players, up to some distance. Think of a map as a grid of cells, then the cell with the player is updated, the 8 cells adjacent to that one, etc up to a max distance (I would assume depending on visibility range). I think that's why NPCs having waypoints stop moving when they go out of sight: they are now in cells not close enough to a player, so these cells aren't updated any more. When you run towards them, they suddenly start moving again, because they are again close enough to players to be in cells that are updated. There is one exception to this rule I believe: active world objects. These are always updated. Then again, making every NPC that has to travel some distance an active world object is probably not recommended.

**Comment by Schmoozerd** [comment]
yes, active objects are updated as if a player was standing right besides them.

And it is very likely and probably a good choice to increase the calculation distance for instances by a few cells.

**Comment by cala** [comment]
Accepted, thank you.

**Pull request closed without merging**
